### ISSUE TITLE
why permission is not end point?

### ISSUE THREAD

**Issue by amin101** [kodeine/laravel-acl#107]
i'm wondering why permission containts multiple items,  i believe  a Role can have multiple Permissions, but it is not meaningfull for me to have permission that it has subset by itself. in this concept Permission convert to something like Role. i mean a permission should point to a single job and a set of these jobs contain a Role and also a set of Roles specify a User  accessibility.
so whats the necessity or idea of deeping down this tree by adding multiple leaf to a permission node?

**Comment by federico77** [comment]
I am looking into Kodeine as well and have been wondering the same thing. Can anyone offer some insight here?

**Comment by eleftrik** [comment]
I totally agree with you, @amin101. I didn't notice this issue (because already closed) so I opened another one ([#179](https://github.com/kodeine/laravel-acl/issues/179)).
Do you still use this package?
