### ISSUE TITLE
Blade Template Extensions in Laravel 5.1

### ISSUE THREAD

**Issue by Hobstweedl** [kodeine/laravel-acl#108]
Blade extensions are not rendering properly in Laravel 5.1. I went to use the role template for the first time and noticed that it displays the literal tag in the view template.

**Comment by amin101** [comment]
can you leave the code here?
do u use {!!  !!} or {{ }} ?

**Comment by Hobstweedl** [comment]
What do you mean? I'm referring to the blade extensions in the wiki

`@role('admin|moderator') `      
    `// content allowed for admin's only `    
`@endrole`        

They don't do anything except display as blade tags to the screen in 5.1

**Comment by feyromain** [comment]
It is necessary add to file routes.php a function.

For example : 
```
Blade::extend(function($view)
{
    return str_replace('@isAdmin', "<?php if(Auth::user()->isAdministrator()): ?>", $view);
});

Blade::extend(function($view)
{
  return str_replace('@endrole', "<?php endif; ?>", $view);
});
```

Then you can use your code

```
@isAdmin
// content allowed for admin's only
@endrole
```

**Comment by Hobstweedl** [comment]
This isn't correct.

First, what you are saying is to extend your laravel app on a case by case basis, instead of using the built in functionality of the package. Creating an `@isAdmin` extension isn't what I was trying to do.

Second, it would be better to extend a Blade function in a service provider.

Third, I only submitted this issue to inform the devs of the package about the issue. It's meant for them to either address the incompatibility introduced in 5.1, or remove the functionality from the package and documentation, or do nothing at all.
