### ISSUE TITLE
Using permissions with multiple authentication

### ISSUE THREAD

**Issue by djoks** [kodeine/laravel-acl#114]
I have about 4 different namespaces in my application each has it's own authentication(user model, user table, user controller).  The reason for this is that i have various portals/views/dashboards accessible by different kind of people and i wanted my data to be independent as much as possible so that nothing i change in one section affects another.

However now my issue is using this package for multiple authentication, this would basically mean 2-3 different user and user role tables.  I realis=ze this may seem odd to some people but as i stated before for certain reasons i need to keep the data separate.

**Comment by kodeine** [comment]
@djoks 
you can always create a role, admin, level1, level2 and assign permissions accordingly to each role.
