### ISSUE TITLE
Laravel 5.2 upgrade

### ISSUE THREAD

**Issue by andreiculda** [kodeine/laravel-acl#116]
Hi,

I just upgraded to Laravel 5.2 and I get an error on any route that uses laravel-acl Roles: 

![image](https://cloud.githubusercontent.com/assets/10087545/12593059/6b511400-c46f-11e5-9757-d2dc02507523.png)

After a long debugging it seems that in laravel 5.2 the [config\auth.php](https://github.com/laravel/laravel/blob/master/config/auth.php) file was changed a "little". 

```javascript
'providers' => [
        'users' => [
            'driver' => 'eloquent',
            'model' => App\User::class,
        ],
        // 'users' => [
        //     'driver' => 'database',
        //     'table' => 'users',
        // ],
    ],
```

In short the laravel-acl [Role.php](https://github.com/kodeine/laravel-acl/blob/1.0/src/Kodeine/Acl/Models/Eloquent/Role.php) model calls a non existing item in:

```javascript
public function users()
    {
        return $this->belongsToMany(config('auth.model'))->withTimestamps();
    }
```

Instead if i change to bellow block it works, the Fatal error disappears and everything is back to normal:

```javascript
public function users()
    {
        return $this->belongsToMany(config('auth.providers.users.model'))->withTimestamps();
    }
```

Is there anything that can be done for the next release of laravel-acl to contain this fix for laravel 5.2?

Thank you.

**Comment by andreiculda** [comment]
Hi @kodeine. Any feedback on this? I would really appreciate it. Thanks.

**Comment by kodeine** [comment]
@andreiculda 
i'll take a look at this today.

**Comment by donnigunawan** [comment]
any news about this? I would like to upgrage to version 5.2 too. Thank you

**Comment by andreiculda** [comment]
@donnigunawan you can update laravel to version 5.2, you just need to tweek [Role.php](https://github.com/kodeine/laravel-acl/blob/1.0/src/Kodeine/Acl/Models/Eloquent/Role.php) as I said above and you application should work like normal, until this issue is fixed.

**Comment by andreiculda** [comment]
Thanks @kodeine and @uzegonemad for the fix. Works great after composer update.
