### ISSUE TITLE
Question: Permission inheritance?

### ISSUE THREAD

**Issue by ssssteve** [kodeine/laravel-acl#12]
Hi Kodeine,

I'm trying to get a handle on this as a Laravel 5 replacement for Entrust. The route protection seems especially useful, and your presence here suggests that this might be a lot better maintained than Entrust seems to be. :thumbsup:

However, I'm not sure if either my scenario or my understanding fits the correct workflow here, as I can't see any form of permission inheritance.

I have set up three roles: webdev, admin, manager and viewer (the latter is probably redundant, but here for completeness)

I can create a permission for managing clients:

```
Permission::create([
                'name'        => 'client',
                'slug'        => [
                    'create'  => true,
                    'view'    => true,
                    'update'  => true,
                    'delete'  => false
                ],
                'description' => 'Manage client permissions'
            ]);
```

However, I would only want to assign those particular permissions to one role, say admin, so as far as I can see in order to make this work I'll need a new permission per role:

```
Permission::create([
                'name'        => 'client.as.admin',
                'slug'        => [
                    'create'  => true,
                    'view'    => true,
                    'update'  => true,
                    'delete'  => false
                ],
                'description' => 'Manage client permissions as admin'
            ]);
```
and I'd attach it to admin with:
```
            $roleAdmin->assignPermission('client.as.admin');
```
So now for 5 models and 5 controllers using 4 roles I have 20 named permissions and 80 'can' permissions (`can('view.client.as.admin')` etc.). To use this in a blade file to determine whether a menu item should be displayed or not I think I need:

```
@if (Auth::user()->can('view.client.as.manager|view.client.as.admin|view.client.as.webdev'))
```

Might this be better if we could use some form of inheritance, or some form of shortened syntax such as 

```
@if (Auth::user()->can('view.client'))
```

Further, your Permissions based on Role section says:

```
$admin = Role::first(); // administrator
$admin->can('view.user');
$admin->canViewUser();  // using method.
```

I read this as the `view` boolean on a single `user` permission, but unless there is just one set of user permissions for all roles, I can''t see how `view.user` could be different for _any_ role other than no role at all. Am I missing something?

**Comment by kodeine** [comment]
Hello @ssssteve,
You can use @if (Auth::user()->can('view.client'));

When you create permissions for client.as.admin just add another param, inherit_id = id of 'client' permission. So view.client.admin will be now be known as view.client since your user will have role of client.as.admin and links to client permission. We start recognizing user as client (inherited permission) and forget client.as.admin. 

I'm sorry I'm not home so I can't write examples since I'm replying you via cell phone. I'll write you examples in few hours.

**Comment by kodeine** [comment]
@ssssteve, Let the example code speak for a better picture.

First we create Roles.
```php
        $roleTeacher = Role::create([
            'name'        => 'Teacher',
            'slug'        => 'teacher',
            'description' => 'Teacher [...]'
        ]);

        $roleStudent = Role::create([
            'name'        => 'Student',
            'slug'        => 'student',
            'description' => 'Student [...]'
        ]);
```

Now lets create Permissions for Teacher and Student.

```php
        $permissionInternship = Permission::create([
            'name'        => 'internships',
            'slug'        => [ // an array of permissions.
                'create' => true,
                'view'   => true,
                'update' => true,
                'delete' => true,
            ],
            'description' => 'manage internships'
        ]);

        $permissionStudent = Permission::create([
            'name'        => 'internships.student',
            'slug'        => [ // an array of permissions only for student
                'create' => false,
            ],
            // we use permission inheriting.
            'inherit_id' => $permissionInternship->getKey(),
            'description' => 'student internship permissions'
        ]);
```
> Note: `inherit_id` in internships.student.
> since `internships.student` inherit permissions from `internships`
we can can forget about `internships.student` because now we recognize it as `internships`.
so getPermissions will return array('internships' => [...permissions merged with internships.student...])


Lets assign those permissions to newly created roles.

```php
$roleTeacher->assignPermission('internships');  // or assignPermission($permissionInternship->id)
$roleStudent->assignPermission('internships.student');
```

And then we can assign those roles to our user.

```php
$user->assignRole($roleTeacher);
$user->assignRole($roleStudent);
//$user->revokeRole('teacher');
```

Finally, lets do our tests.

```php
// user has teacher and student role
dump($user->can('create.internships')); // results true

// user has teacher role
dump($user->can('create.internships')); // results true

// user has student role
dump($user->can('create.internships')); // results false

dump($user->getPermissions());
```

**Comment by ssssteve** [comment]
Hi @kodeine, thanks very much for your extremely rapid response. That sounds just right, and having just modified my Permissions seeder it seems to work really well.

Just as an added example, I'll mention that I'm doing it slightly differently to your example, which might be somewhat safer. I've set up a top level Permission but set all the permissions to `false`:
```php
 $clientPermission = Permission::create([
                'name'        => 'client',
                'slug'        => [
                    'create'   => false,
                    'view'     => false,
                    'update'   => false,
                    'delete'   => false,
                    'suspend'  => false
                ],
                'description' => 'Manage client permissions'
            ]);
```
I can then set specific permissions `true` on a per role basis:
```php
            Permission::create([
                'name'        => 'client.as.webdev',
                'slug'        => [
                    'create'  => true,
                    'view'    => true,
                    'update'  => true,
                    'delete'  => true,
                    'suspend' => true
                ],
                'inherit_id' => $clientPermission->getKey(),
                'description' => 'Manage client permissions as webdev'
            ]);

            $roleWebdev->assignPermission('client.as.webdev');
```
and for the lowest level role:
```php
            Permission::create([
                'name'        => 'client.as.viewer',
                'slug'        => [],
                'inherit_id' => $clientPermission->getKey(),
                'description' => 'Manage client permissions as viewer'
            ]);

            $roleViewer->assignPermission('client.as.viewer');
 ```

This way permissions are explicitly set if required, and adding a new permission should be inherited safely until overridden for a specific role.

Thanks for your help!

**Comment by kodeine** [comment]
@ssssteve, you're welcome :)
