### ISSUE TITLE
in_array() throws error in laravel 5.2

### ISSUE THREAD

**Issue by lokimo** [kodeine/laravel-acl#120]
I got an 

> expects parameter 2 to be array, object given

error from

```
    // single slug
    return in_array($slug, $roles);
```

[(here)](https://github.com/kodeine/laravel-acl/blob/75f23745b65d76d9974ab2a1adabe2b337ec5618/src/Kodeine/Acl/Traits/HasRole.php#L83) although [Illuminate\Support\Collection](https://laravel.com/api/5.2/Illuminate/Support/Collection.html) implements ArrayAccess it dosen't seem to work.

When I do 

```
    // single slug
    return $roles->contains($slug);
```

it's fine. Seems like passing an ArrayAccess implementing object won't work at all (http://stackoverflow.com/questions/8788002/arrayaccess-and-native-php-array-functions?rq=1)

**Comment by Messhias** [comment]
This project seems to be abandoned, so I forked to my open-source saver organization and we're willing to continue the contribution of the project, we did that already before with Tymon's Design JWT package for laravel. 

You can access the package here -> https://github.com/kodeine/laravel-acl/pull/266
