### ISSUE TITLE
Error $roleAdmin->assignPermission(Permission::all());

### ISSUE THREAD

**Issue by dead23angel** [kodeine/laravel-acl#122]
Using 
```php
$roleAdmin = Role::first(); // administrator
$roleAdmin->assignPermission(Permission::all());
``` 
we get an error 
```                                              
  Object of class Illuminate\Database\Eloquent\Collection could not be conver  
  ted to int
```
the problem in this code
```php
$model = '\Illuminate\Database\Eloquent\Model';
if ( is_object($permission) && $permission instanceof $model ) {
       $permission = $permission->getKey();
}
```
because in the variable $permission = Illuminate\Database\Eloquent\Collection
сonsequently $permission instanceof $model = FALSE

Sory my sad english

**Comment by arcanedev-maroc** [comment]
Hi @dead23angel,

The `assignPermission($permission)` method accepts only one permssion, not a permissions collection.

But honestly, i'm a little bit confused about this method (judging by its name). Try the `syncPermissions($permissions)` method and see if it fix your issue.

**Comment by dead23angel** [comment]
Hi @arcanedev-maroc 

Namely, it can take only one value, and in the documents written by example, and there is just a collection of transfer in this method. I did so at
```php
$roleAdmin->assignPermission('users, cars');
```

**Comment by dead23angel** [comment]
I'm sorry it turned out I had to install the version 0.1.3 this bug and it was updated to 1.0@dev problems disappeared
