### ISSUE TITLE
Multiple groups in routes

### ISSUE THREAD

**Issue by subdesign** [kodeine/laravel-acl#13]
How to add multiple groups like I do in Sentry with filters?

Sentry:
```php
'before' => 'inGroup:administrator,editor|hasAccess:users.show'
```
so this works?
```php
...
'is' => 'administrator,editor',
'can' => 'create.user, delete.user'], 
```
thanks

**Comment by kodeine** [comment]
@subdesign, Yes are right, you can use `is` and `can` params. But notice the use of comma, it will be referred as `user` is admin `and` editor. If you use pipe |, it will be referred as `user` is admin `or` editor. Same goes with `can` method.
