### ISSUE TITLE
Share routes between roles

### ISSUE THREAD

**Issue by viaro-ari** [kodeine/laravel-acl#130]
How can I do to have a route and allow it to be available for different user roles?

This is my current code
        Route::group(array('middleware' => 'acl' , 'is' => 'superadmin' ), function()

I want to do something like this
        Route::group(array('middleware' => 'acl' , 'is' => 'superadmin|administrator' ), function()

**Comment by kodeine** [comment]
@viaro-ari yes that logic will work, you can try it :)
