### ISSUE TITLE
Different Providers not supported

### ISSUE THREAD

**Issue by sajin577** [kodeine/laravel-acl#135]
In case someone uses a provider other than default "user" provider in laravel, this package will not handle it.

While assigning the role, I got an error.

 Base table or view not found: 1146 Table 'vibrant_test.admin_role' doesn't exist (SQL: select `roles`.*, `admin_role`.`admin_id` as `pivot_admin_id`, `admin_role`.`role_id` as `pivot_role_id`, `admin_role`.`created_at` as `pivot_created_at`, `admin_role`.`updated_at` as `pivot_updated_at` from `roles` inner join `admin_role` on `roles`.`id` = `admin_role`.`role_id` where `admin_role`.`admin_id` = 1)'

How can we resolve the issue? New migrations can be created, but how we need to reconfigure config/acl.php as it supports only one model?

**Comment by sajin577** [comment]
* Guard, not providers. I stand corrected.

**Comment by kodeine** [comment]
@sajin577 were you able to fix this issue? you can propose a PR?
