### ISSUE TITLE
Fatal Error in User.php (line 8)

### ISSUE THREAD

**Issue by gkimpson** [kodeine/laravel-acl#138]
I've added all of the Kodeine Laravel ACL files and am trying to create a user in the users table with the generated form Laravel creates when you do php make:auth in Laravel 5.2

I am always getting the error - can someone explain what I have done wrong?

https://gist.github.com/gkimpson/9407d8e404143b1f40edb3b8821290d2

FatalErrorException in User.php line 8:
Class 'App\Model' not found

**Comment by anarcist69** [comment]
@gkimpson You need to add `use Illuminate\Database\Eloquent\Model;`

To the top of your User.php file
