### ISSUE TITLE
Installation guide not up-to-date with Laravel 5.2 User model?

### ISSUE THREAD

**Issue by Seroczynski** [kodeine/laravel-acl#140]
There seems to be an unattended issue in the [Installation guide](https://github.com/kodeine/laravel-acl/wiki/Installation). Both these threads make mention of the errors that are given when a clean Laravel project is being used:
- [Interface 'AuthenticatableContract' not found](https://github.com/kodeine/laravel-acl/issues/131)
- [Fatal Error in User.php (line 8)](https://github.com/kodeine/laravel-acl/issues/138)

The problem lies with the final step in the [Installation guide](https://github.com/kodeine/laravel-acl/wiki/Installation):

> **Model Setup**
> Next, add the `HasRole` trait to your User model:
> 
> ```
> use Kodeine\Acl\Traits\HasRole;
> 
> class User extends Model implements AuthenticatableContract, CanResetPasswordContract
> {
>     use Authenticatable, CanResetPassword, HasRole;
> }
> ```

A fresh Laravel 5.2 installation has the following User model included:
```
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    ...
}
```

Now I'm new to Laravel, so I might be wrong, but simply changing the User class to extend the Model class won't solve this problem since then you would get the `Interface 'AuthenticatableContract' not found` error.

I'd very much like to start using this package. Any help is appreciated.

**Comment by boynet** [comment]
don't change the extended model or anything else in there just add the HasRole trait
```
class User extends Authenticatable
{
    use HasRole
.....
```

**Comment by Seroczynski** [comment]
Thanks a ton! This seems to have fixed any error messages I previously had.

**Comment by udemethegrtman** [comment]
@boynet you have really solved the headache i have been having for weeks.
