### ISSUE TITLE
Check both role and permissions

### ISSUE THREAD

**Issue by securit** [kodeine/laravel-acl#148]
Is it possible in the blade to check both the users Roles they belong to and their permissions? Or should I simply be checking their permissions and will those flow from the roles a user belongs to?

**Comment by kodeine** [comment]
@securit you can definately check permissions, check this [wiki post](https://github.com/kodeine/laravel-acl/wiki/Blade-Extensions)

**Comment by kodeine** [comment]
reopen this if you need help.
