### ISSUE TITLE
assignPermission with object argument

### ISSUE THREAD

**Issue by nglelinh** [kodeine/laravel-acl#15]
Following the wiki instruction:

$roleAdmin = Role::first(); // administrator
$roleAdmin->assignPermission($permUser);

I got 

InvalidArgumentException in HasPermission.php line 157:
Specified permission name does not exists.

Function assignPermission works well when assign by id or name

**Comment by kodeine** [comment]
@nglelinh, please write more source so i can run it here and try easily.
