### ISSUE TITLE
Wile checking permission what exactly need to pass permission name or permission slug for can method.

### ISSUE THREAD

**Issue by sonaliraut29** [kodeine/laravel-acl#157]
Here is my code.

$role = Role::where('id', '=', $roleId)->get()->first(); 
 if(!$role->can('??')) { // here what should we pass permission name or slug
   // do something
}

**Comment by kodeine** [comment]
@sonaliraut29 you can pass either id, slug or the object itself. I usually prefer passing the whole object.

you may open this if you need further help.
