### ISSUE TITLE
Wrong permission for user without role

### ISSUE THREAD

**Issue by nglelinh** [kodeine/laravel-acl#16]
Get a user without any role, for example

$testUser = User::find(4);

add permission to him

$testUser->addPermission('create.user');

$testUser->can('create.user') returns false

But if I assign him to any role, even which this roles doesnt relate to that permission, I get right answer.

Please check.

**Comment by kodeine** [comment]
@nglelinh, please try again, i've pushed fixes.

**Comment by nglelinh** [comment]
It works well now. Thank you.
