### ISSUE TITLE
Laravel 5.3 upgrade breaks core feature

### ISSUE THREAD

**Issue by parvathis** [kodeine/laravel-acl#160]
Hello,

I recently tried to upgrade my application from Laravel 5.2 to 5.3 and I am having issues with the acl middleware ever since. I could track the issue to a Laravel helper function update in 5.3.

Kodeine\Acl\Middleware\HasPermission.php uses array_where() helper function to determine the crud that we're trying to protect. In 5.3, $value and $key variables have been reversed and this breaks the checking.

Could you please modify this and bring up an intermittent release?

**Comment by kodeine** [comment]
@parvathis can you please send a PR?

**Comment by parvathis** [comment]
@kodeine Done.
