### ISSUE TITLE
Requesting video tutorials

### ISSUE THREAD

**Issue by PSNAppz** [kodeine/laravel-acl#162]
Laravel-acl is one of the best ACL for Laravel as far as I know. As a beginner I recommend if some one could post a video tutorial on youtube covering all the basic to advanced features of this project it would be very helpful. I have been searching for a good tutorial on this acl but unfortunately I couldn't find any.

Regards,
_**PSN**_

**Comment by datune** [comment]
As an expert I would recommend you start by reading the excellent wiki from start to finish. If you do not understand this simple package from the manual, I really doubt a video tutorial would make much of a difference.
