### ISSUE TITLE
Role has permission

### ISSUE THREAD

**Issue by amandiobm** [kodeine/laravel-acl#165]
How I check if a Role has a permission on it?

**Comment by QuentinPetel** [comment]
See the wiki :
https://github.com/kodeine/laravel-acl/wiki/Validate-Permissions-and-Roles

## Validate Permissions

Permissions can be validated by calling can method.

### Validate based on Role.

Method can() supports comma for AND and pipe as OR operator. Or you can pass operator as a second param.
`$admin = Role::first(); // administrator`
`$admin->can('view.user');`
`$admin->canViewUser();  // using method.`

// by an array
`$admin->can(array('view.user', 'edit.user'));`

// by an array with or operator
`$admin->can(array('view.user', 'edit.user'), 'or');`

// using pipe as OR operator
// any allowed permission will result to true.
`$admin->can('view.user|edit.user|view.admin|delete.admin');`

// using comma as AND operator
// all permissions defined must be allowed to result true.
`$admin->can('view.user,edit.user,view.admin,delete.admin');`
