### ISSUE TITLE
About get user permissions

### ISSUE THREAD

**Issue by nglelinh** [kodeine/laravel-acl#17]
In Wiki i found the following rules about user permissions

1) getPermissions : Get permissions assigned to a user, all user permissions along with its role permissions.
2) user permissions override role ones.

But I dont get them as result. Please refer this image

http://snag.gy/Eyc6Y.jpg

Please check.

**Comment by kodeine** [comment]
@nglelinh, please write me the code to test.

**Comment by kodeine** [comment]
@nglelinh, by looking at the screenshot, it seems like your role permissions are not ending with .post but your user permissions are ending with .post. Make sure your role has a permission xxx.post and if user has same *.post it will override. If you give me your code i can help more easily.

**Comment by nglelinh** [comment]
@kodeine: I have just retested on a fresh new db. 

Create new objects:
               $testUser = User::create([
			'name' => 'tester',
			'email' => 'test@mail.com',
			'password' =>'$2y$10$5QYFCfkd5lSOxX20i0w2p.hwSupOP.YcJxRRoL8073FzXQXADTDZy']
		);
		$testRole = Role::create([
			'name' => 'newRole',
			'slug' => 'newrole',
			'description'=>'a new test role'
		]);
		$permHouse = Permission::create([
			'name'        => 'house',
			'slug'        => [
				'create'     => true,
				'view'       => true,
				'update'     => true,
				'delete'     => true,
			],
			'description' => 'manage house permissions'
		]);

And then run:
		$testRole->assignPermission($permHouse); 
		$testUser->assignRole($testRole);
		$testUser->addPermission('create.house', false);
		return [
			'$testUser->roles->slug' => $testUser->roles->lists('slug'),
			'$testRole->permissions->slug' => $testRole->permissions->lists('slug'),
			'$testUser->permissions->slug' => $testUser->permissions->lists('slug'),
			'$testUser->getPermissions()' => $testUser->getPermissions(),
			'$testUser->can("create.house")' => $testUser->can('create.house')
		];

**Comment by kodeine** [comment]
@nglelinh, My last commit should fix this issue, please try again and confirm.

**Comment by nglelinh** [comment]
The second part has been fixed. Permission by user overwrites permission by role.

But the first part still hasn't. Expect result for : $testUser->getPermissions() 
{
create: false,
view: true,
update: true,
delete: true
}

Btw, I can not remove user permission now by executing: $testUser->removePermission('create.house').

Please check again. Thank you

**Comment by kodeine** [comment]
@nglelinh I didn't get what's not working other than remove permission

**Comment by nglelinh** [comment]
@Kodeine: As I understand, user permissions (result of $user->getPermissions()) are combination of permissions by role and permission by user.
In this example, $testUser has permission from role
{
create: true,
view: true,
update: true,
delete: true
}
and his own permission
{
create: false
}
so the result should be as I mentioned above. Please correct if I am wrong.

**Comment by kodeine** [comment]
@nglelinh, somehow my latest commit was not pushed, i have pushed it now and confirmed. Please check at your end. Thanks

**Comment by nglelinh** [comment]
@kodeine: The combination roles is ok now. But still can not remove user's permission by executing
$testUser->removePermission('create.house')

**Comment by kodeine** [comment]
@nglelinh, please try now, it should be fixed.

**Comment by nglelinh** [comment]
@kodeine: thank you. It works well now.
