### ISSUE TITLE
handling protected route 

### ISSUE THREAD

**Issue by t0n1zz** [kodeine/laravel-acl#172]
so if i have user that are not authorized to view some get route then i will throw HttpException and showing message You are not authorized to access this resource.

but if i want to costumize the way user being directed because he tried to access unauthorized view? how to point it into some php page that i created for telling user that he/she don't have access to go to this page?

**Comment by QuentinPetel** [comment]
Using a redirection : https://laravel.com/docs/5.3/responses#redirects

**Comment by kodeine** [comment]
You may reopen this if you still need help on this.

**Comment by t0n1zz** [comment]
i am sorry, for responding answer right now, i just got busy these few days...
hmm can you give me some example please?

**Comment by QuentinPetel** [comment]
The 'can' throw an HTTPException with abort(401, 'You are not authorized to access this resource.'); if user has insufficient permissions.

I think that you can intercept this exception in the ExceptionHandler (App/Exceptions/Handler). I haven't test that but in the render method, you could do something like : 

    public function render($request, Exception $e)
    {
        if ($e->getMessage() == 'You are not authorized to access this resource.') {
           return redirect('home/dashboard'); // By URL
           // or
           return redirect()->route('login'); // Or by whatever the named route you wan't to redirect your user.
        }
        return parent::render($request, $e);
    }
