### ISSUE TITLE
Fatal error raised when xdebug enabled 

### ISSUE THREAD

**Issue by omidahn** [kodeine/laravel-acl#174]
Hi, I'm trying to generate code coverage report, so i have xdebug enabled which causes this ERROR : 

`PHP Fatal error:  Uncaught Error: Undefined class constant 'VERSION' in /home/vagrant/Code/my-project/vendor/kodeine/laravel-acl/src/Kodeine/Acl/Traits/HasRole.php:270`

laravel 5.3.24 - PHP : 7.0.12 - PHPUnit 5.6.7

it refers to this line :
`if (version_compare($laravel::VERSION, '5.3', '<')) {`
I think , having different branch for older versions of  laravel is the perfect solution.

**Comment by omidahn** [comment]
appears to be my own testcase implementation problem

**Comment by vjandrea** [comment]
Same problem here with phpunit while trying to generate code coverage, I will propose a PR that checks if $laravel::VERSION exists.

**Comment by vjandrea** [comment]
I created the pull request that did check if `$laravel::VERSION` was not null, but after upgrading PHP to 7.1 the error appeared again so i had to cancel it.
I tried then with the class method `$laravel->version()`, the result should be the same but i saw that for phpunit`$laravel` is not an instance of `\Illuminate\Foundation\Application`, but instead appears as an instance of `Illuminate\Container\Container`, i'm not sure if this is correct.

    Error: Call to undefined method Illuminate\Container\Container::version() in /./vendor/kodeine/laravel-acl/src/Kodeine/Acl/Traits/HasRole.php on line 284

**Comment by Strift** [comment]
Hello, does anyone know how to fix this?

**Comment by vjandrea** [comment]
Hello Strift, i am waiting for my [pull request](https://github.com/kodeine/laravel-acl/pull/195/) to be merged.

**Comment by kodeine** [comment]
Give me an hour or two and ill merge those.

**Comment by kodeine** [comment]
@Strift @vjandrea its been merged. thanks.
