### ISSUE TITLE
Duplicate permissions created when assigning to user.

### ISSUE THREAD

**Issue by mcblum** [kodeine/laravel-acl#175]
Hi!

Thank you for this package. Here's my code to create the permission:

```php
$permissionSupport = Permission::create( [
			'name'        => 'support',
			'slug'        => [
				'access' => true
			],
			'description' => 'access our support module'
		] );
```

```php
$user->addPermission( 'support', [
			'access'    => true
		]);
```

Yet every time I do this, a new permission is created. Am I doing something wrong?

**Comment by mcblum** [comment]
I've also tried `$user->addPermission(1)` using its ID and `$user->addPermission('access.support', true)`

**Comment by mcblum** [comment]
Never mind! I guess I needed `assignPermission()`. Not sure how I missed that in the docs...

**Comment by kodeine** [comment]
@mcblum let me know if you still face any problems, you may reopen this.
