### ISSUE TITLE
[Suggestion] Role Inheritance

### ISSUE THREAD

**Issue by AlbertMarashi** [kodeine/laravel-acl#176]
I've been trying to modify your package to try and implement a Role inheritance feature but I've had a bit of trouble, I lack advanced PHP skills.

Eg: 
```
owner has X permissions
superadmin has Y permissions
admin has Z permissions

Superadmin inherits all of admin
Owner inherits all of superadmin

Owner can do X + Y + Z
Superadmin can do Y + Z
Admin can do Z
```

I'm sure a lot of people would appreciate this feature, rather than having to apply the same permissions to every higher level of a role. Can we please get this?

**Comment by kodeine** [comment]
@MrMashy please refer to this [wiki page](https://github.com/kodeine/laravel-acl/wiki/Permissions-Inheritance)
