### ISSUE TITLE
Roles for companies too

### ISSUE THREAD

**Issue by lsobral** [kodeine/laravel-acl#189]
Is it possible to use with other tables besides the User table? Ex. I have a Companies table that I would like to have roles too. I have User and Companies with roles. Thanks

**Comment by konovalov-nk** [comment]
@lsobral Probably you can solve it by creating a user named as a company and assign roles to that user. Add columns (`type='person,company,etc'`, `reference_id='0,$company_id,etc'`) to the user table indicating if the user is the real person or company/entity.

**Comment by lsobral** [comment]
Thanks @konovalov-nk for your tip. I have 2 tables.
User (laravel default) and Company tables.
I want to use roles for both.

**Comment by konovalov-nk** [comment]
@lsobral 
This is impossible at the moment without modifying the source code. `role_user` table holds the info for roles assigned to a single table. It could be either `company` or `user`, but not both.

To make it possible, `role_user` table must include `table` name column it would refer to, and `id`, `table` keys would be a composite primary key. In that case, `role_user` would be called `role_entity` or something like that. And you have to modify all the code that checks entity roles, gets the permissions, checks for user permissions, etc.

**Comment by lsobral** [comment]
ok @konovalov-nk thanks a lot.
