### ISSUE TITLE
Class 'Role' not found in eval()'d code on line 1

### ISSUE THREAD

**Issue by int-m** [kodeine/laravel-acl#19]
Hello,

i think i make an failure on installation.

on php artisan tinker i try do add a role but get the following error.

>>> $roleAdmin = new Role();
PHP Fatal error:  Class 'Role' not found in eval()'d code on line 1

Please help me. I am very new on laravel.

**Comment by kodeine** [comment]
@int-m, you need to use name space. 
```php
$roleAdmin = new \Kodeine\Acl\Models\Eloquent\Role();

// or you can set these on top.
use Kodeine\Acl\Models\Eloquent\Permission;
use Kodeine\Acl\Models\Eloquent\Role;
```

**Comment by int-m** [comment]
Thank you so much.

**Comment by akanbitoluwase** [comment]
Hello,

I am having a similar challenge and even after using the namespace I still get errors as seen below:

Psy Shell v0.5.2 (PHP 5.5.20 — cli) by Justin Hileman
>>> namespace todoparrot;
=> null
>>> $list = new Todolist;
PHP Fatal error:  Class 'todoparrot\Todolist' not found in eval()'d code on line 1

Kindly help out on this
