### ISSUE TITLE
Question: Entrust

### ISSUE THREAD

**Issue by rzimin** [kodeine/laravel-acl#2]
Greetings,

Just wonder. Reading the specs for Entrust and for me as a beginner it actually looks quite similar with laravel-acl. I also saw your comments on "If package is still alive" issue for Entrust. so it seems you just wanted to create something for yourself instead of waiting for compatibility with L5 :+1: 

I mean I just try to find what is different and what are the killer features for laravel-acl as I would really like to use this one. Probably you can just share some thoughts you had while creating yours?

Cheers,
Roman.

**Comment by kodeine** [comment]
hello @rzimin,

I had used entrust and sentry in the past but was not quite happy. Guess i needed something more friendly while keeping things elegant. Laravel-acl uses Roles based permissions and permissions are based on Aliases. Aliases are a set of permissions. For example, lets assume we have a `User` role. For permissions we can create an Alias, as User. That alias has all the permissions needed for user. So our crud (create, read, view, update, delete) permissions along with view.phone (as an example) are set to permission alias of user. So specific user permissions only belong to user alias. Permissions on entrust are depending on roles.

Laravel-acl checks for user permissions override. For example, if all users are not allowed to  `view.phone` but you need one user exclusively to be able to `view.phone`, you can simply assign that permission to your user and his exclusive rights will override the role permissions.

More over, laravel-acl supports protecting crud methods on routes. So if you want to protect editing and deletion of content you can simply do that from routes. Just tell your routes which alias to use for crud permissions and acl does the rest of the job. 

> Of course you will have to set create.user, read.user,  update.user etc permissions for user alias. 

If your controller uses resource methods like (index, create, store etc) Acl will know that and protect them, if you have different method names (not resource methods) it will go with restful (http methods [GET, POST, PUT] etc. If none of those are viable in your case you can define your own method names to protect.

All these things were needed in my projects and i wanted full control on them so i came up with laravel-acl. Hope it will help serve your purpose. Feel free to write your suggestions/comments/critics.

**Comment by rzimin** [comment]
> Shut up and take my money. (c)

Thanks for detailed answer. Would definitely give it a try!
