### ISSUE TITLE
Assing specific permissions to roles

### ISSUE THREAD

**Issue by Mythos** [kodeine/laravel-acl#21]
Hi, is it possible to assign only specific permissions to roles?

According to the wiki it's possible to do this by following line:

```
$roleAdmin->assignPermission('user');
```

But in my case I want my roles to only have something like this:
```
$roleUser->assignPermission('view.user');
$roleModerator->assignPermission(['view.user', 'update.user']);
$roleAdmin->assignPermission('user');
```

So is this possible with the code above or is it a feature that has to be implemented?

Regards,
Stefan

**Comment by kodeine** [comment]
@Mythos, its not a good idea to split user permissions into different roles. Better make a role user and then assign permissions to it. 

Or if i am seeing this right, you are trying to split admin and moderator permissions. For this you can use permission inheriting.

Please look at this [wiki](https://github.com/kodeine/laravel-acl/wiki/Permissions-Inheritance)

If you need help with example codes, feel free to let me know and ill help you

**Comment by Mythos** [comment]
I think permission inheritance will fix my problem, thanks.

**Comment by Mythos** [comment]
Now I have a problem creating my "parent" permission because of the new foreign key for `inherit_id` added 2 days ago.

```
  [Illuminate\Database\QueryException]                                                                                                                                                                                                                             
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`todo`.`permissions`, CONSTRAINT `permissions_inherit_id_foreign` FOREIGN KEY (`inherit_id`) REFERENCES `permissions` (`id`)) (SQL: ins  
  ert into `permissions` (`name`, `slug`, `description`, `updated_at`, `created_at`) values (user, {"create":true,"view":true,"update":true,"delete":true}, Permissions for managing users, 2015-03-16 17:20:30, 2015-03-16 17:20:30))                             
                                                                                                                                                                                                                                        
  [PDOException]                                                                                                                                                                                                                                         
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`todo`.`permissions`, CONSTRAINT `permissions_inherit_id_foreign` FOREIGN KEY (`inherit_id`) REFERENCES `permissions` (`id`)) 
```

**Comment by kodeine** [comment]
@Mythos, please try the dev-dev branch, i have updated the permission inheritance. You can use inherit_id if you want to but if not, permission names must be common and they will be inherited. Secondly, you can set the `NTFS right`(more permissive wins) in config.

**Comment by Mythos** [comment]
@kodeine 
I'll reopen this issue for now.
I'll test your changes in the dev-branch tonight. 
But what does NTFS mean? You mean the filesystem? And what do these changes exactly?

**Comment by kodeine** [comment]
@Mythos 
NTFS right, the more permissive wins
If you have multiple permission aliases assigned, each alias
has a common permission, view.house => false, but one alias
has it set to true. If ntfs right is enabled, true value
wins the race, ie the more permissive wins.

**Comment by Mythos** [comment]
@kodeine 
So if i want for example this:
```
Administrator:
 - user.view = true
 - user.edit = true
 - user.delete = true
 - user.create = true

Moderator:
 - user.view = true
 - user.edit = true
 - user.delete = false
 - user.create = false

User:
 - user.view = true
 - user.edit = false
 - user.delete = false
 - user.create = false

```

What do I have to do exactly?
Also please note that I want to edit roles and permissions via an ACP so the permissions assigned to a role will change. I want to manage roles (create, edit, delete) and assign/remove permissions to them.

**Comment by kodeine** [comment]
```
Administrator:
 - user.view = true
 - user.edit = true
 - user.delete = true
 - user.create = true
 - user.view_phone = true

Moderator: --> set inherit_id to Administrator
 - user.view = true
 - user.edit = true
 - user.delete = false
 - user.create = false

User: --> set inherit_id to Administrator or Moderator
 - user.view = true
 - user.edit = false
 - user.delete = false
 - user.create = false
```
> if u use inherit_id param while creating permissions.
So if user has a role of `user`, he will be able to `view` , and `view_phone`. Notice the `view_phone` being inherited from `Administrator` role. Similarly if user has a `Moderator` role, he will be able to `edit view and view_phone`.

> if ntfs is set to true, and user has `user` and `admin` and other roles. One of the role has user.view.phone to true and all others deny it. Ntfs will use more permissive so since user.view.phone was found to be true in one of the roles so it will end up true.

**Comment by Mythos** [comment]
@kodeine 
Ok that's exactly what I want.
But how do I create a role/permission management?
My plan is to have a menu item for Roles, where I can create/edit/delete them. In the view/edit view I would have checkboxes for assigning and removing permissions for that role.

If I have e.g. a User role with permissions inheriting from my Administrator role, will I have all permissions (including the inherited ones)?

E.g.
```
Administrator Role:
 - post.create = true
 - post.edit = true
 - post.view = true
 - post.delete = true

User Role inheriting from Administrator Role:
 - post.delete = false
```

So would something like this be possible:
```
$UserRole->getAllPermissions();  // Returns [post.create = true;post.edit = true; post.view = true; post.delete = false]
```
Also how will I bind checkboxes to those permissions as they are not independent objects?

**Comment by kodeine** [comment]
@Mythos 
I guess there are two ways which we can do this.

1. make a new function getRawPermissions() which will return permissions without inheriting but with the permission ids etc.
2. getPermissions() returns without inheriting, getPermissions($inherit = true) will return inherited like it does now.

What you think?

**Comment by Mythos** [comment]
@kodeine 
I think option 2 would be fine as you don't have to create a new function to remember, just a parameter. ;-)

**Comment by kodeine** [comment]
@Mythos 
I have added a new function, `getPermissionsRaw()`, tell me if that works for you.
(dev branch).

**Comment by kodeine** [comment]
@Mythos 
Or you can try
```php
dump($user->permissions->toArray());
```

**Comment by RomainLanz** [comment]
Closed due to inactivity.
