### ISSUE TITLE
You are not authorized to access this resource.

### ISSUE THREAD

**Issue by missionphp** [kodeine/laravel-acl#217]
this is my route
------------------------------------------------------
Route::group(['middleware' => ['web','auth']], function () {
    Route::group(['protect_alias' => 'farmer'], function () {

        Route::resource('farmer', 'FarmerController');

    });
    Route::group(['middleware'=>['acl'],'protect_alias' => 'office'], function () {

        Route::resource('office', 'OfficeController');
    });
});

----------------------------------------------------------------------

I am trying following url to access 
http://localhost/lastpract/public/office

----------------------------------------------------------------------

but I am getting following error 

You are not authorized to access this resource.

I am using laravel 5.2
--------------------------------------------------------------------------
my RoleController's store method is as follow

 public function store(Request $request)
    {

        DB::beginTransaction();

        $add = $request->add;
        $view = $request->view;
        $edit = $request->edit;

        $role = new Role();

        $roleModerator = $role->create([
            'name' => $request->role_name,
            'slug' => $request->role_name,
            'description' => 'manage moderator privileges'
        ]);

        if (!$roleModerator) {
            DB::rollBack();
            return redirect()->back()->withErrors('uanble to create role');
        }
        //permission

        $permission1 = new Permission();
        foreach ($request->name as $k => $permission) {

          //  if (isset($add[$k]) || isset($view[$k]) || isset($edt[$k])) {
                $permPost = $permission1->create([
                    'name' => $permission,
                    'slug' => [          // pass an array of permissions.
                        'create' => isset($add[$k]) ? true : false,
                        'view' =>true,
                        'update' => isset($edt[$k]) ? true : false,
                        'delete' => isset($edt[$k]) ? true : false,
                    ],
                    'description' => 'manage post permissions'
                ]);
                if (!$permPost) {
                    DB::rollBack();
                    return redirect()->back()->withErrors('uanble to create role');
                } else {
                    $roleModerator->assignPermission($permPost->id);
                  //  $roleModerator->syncPermissions([$permPost->id]);
                }
          // }

        }

        DB::commit();
        echo "added succesffully";

    }
____________________________________________________________________________________

and my user controller's store method  is as follow

 public function store(Request $request)
    {

        DB::beginTransaction();

        $user = User::create(
            [
                'name' => $request->name,
                'email' => $request->email,
                'password' => bcrypt($request->password),
                'role'=>$request->role

            ]
        );

        if (!$user) {
            DB::rollback();
            return redirect()->back()->withErrors('unable to create user');
        }

        $user_permission=Role::where('id',$request->role)->value('slug');;
        $user->assignRole($request->role);
        $user->addPermission($user_permission);
        DB::commit();
        echo 'user created successfully';
    }

can anybody tell me what is issues

**Comment by ChaosPower** [comment]
This package requires laravel 5.5+
