### ISSUE TITLE
FatalErrorException in HasPermissionInheritance.php line 57:

### ISSUE THREAD

**Issue by limweb** [kodeine/laravel-acl#23]
FatalErrorException in HasPermissionInheritance.php line 57:
Call to a member function getKey() on a non-object
in HasPermissionInheritance.php line 57

**Comment by limweb** [comment]
// ---- get user by id
public function getUserbyid($id){
	$u = User::find($id);
		$u->getPermissions();
		$u->getRoles();
	dump($u);	
}

Error at call this function

Thanks.

**Comment by limweb** [comment]
in   line 21          
foreach ($inherits as $name => $inherit_id) {
 if ( is_null($inherit_id)  ) continue;
   I'm change to 
   if ( is_null($inherit_id) || empty($inherit_id) ) continue;

in database   field is int   can't be null  is  will fill   zero 0

**Comment by Mythos** [comment]
Is your column nullable? If not you have to alter it to be nullable as this has been changed in 4f6ffd453a2d4dbcc9de9febd05476aa0d92de39 due to #21

**Comment by kodeine** [comment]
@Mythos @limweb So FatalErrorException is fixed because of 4f6ffd453a2d4dbcc9de9febd05476aa0d92de39 right? Here i dont see that exception.

**Comment by limweb** [comment]
thanks.

**Comment by Mythos** [comment]
@limweb 
Has this fixed your problem?

**Comment by kodeine** [comment]
@Mythos @limweb 

This should be fixed now as i pushed it with `is_null($inherit_id) || empty($inherit_id)` this way for other people their apps wont break by not having nullable() in their inherit_id field.
