### ISSUE TITLE
Laravel 6.0

### ISSUE THREAD

**Issue by stygiansabyss** [kodeine/laravel-acl#233]
Is there any chance of this working for laravel 6.0?  The `~5.0` will no longer work anymore.

**Comment by rhofma** [comment]
Hope there will be a solution :(

**Comment by kodeine** [comment]
can any one you submit a PR? i'm on a vacation these days so wont be able to quickly upgrade.

**Comment by alec-joy** [comment]
That works for me, the new version would have to support PHP 7.2+ since that's the lowest version Laravel/Illuminate 6.0 support. I will get a PR up for that today and change the TravisCI file for that branch to test on 7.2 and 7.3 only

**Comment by kodeine** [comment]
Thanks guys!

**Comment by kodeine** [comment]
@alec-joy if you get time, can you please update the wiki/readme and remove any migration changes we did maybe readme is reflecting to old method.

**Comment by alec-joy** [comment]
By migration changes do you just mean what I had to do to make the package 6.0 compatible? I didn't make changes to the actual migration files (though i realize it says I did, I'm working on a Windows machine at the moment and I forgot to check the line endings before committing so it says I modified almost everything)

**Comment by kodeine** [comment]
aa okay, makes sense. Please change the wiki/readme as needed so others can know about the changes. Thank you!
