### ISSUE TITLE
Library is doesn't migrate files

### ISSUE THREAD

**Issue by mustafat0k** [kodeine/laravel-acl#249]
I did try few times but every project given error. I think reason is bigInteger

   Illuminate\Database\QueryException  : SQLSTATE[HY000]: General error: 1215 Cannot add foreign key constraint (SQL: alter table `role_user` add constraint `role_user_user_id_foreign` foreign key (`user_id`) references `1` (`id`) on delete cascade)

  at C:\Users\casper\Desktop\acl\vendor\laravel\framework\src\Illuminate\Database\Connection.php:669
    665|         // If an exception occurs when attempting to run a query, we'll format the error
    666|         // message to include the bindings with SQL, which will make this exception a
    667|         // lot more helpful to the developer instead of just the database's errors.
    668|         catch (Exception $e) {
  > 669|             throw new QueryException(
    670|                 $query, $this->prepareBindings($bindings), $e
    671|             );
    672|         }
    673|

  Exception trace:

**Comment by hacicavcav** [comment]
i figure out the issue but why i still seeing old repo when i include library in my project.        "kodeine/laravel-acl": "^2.0", 
When i updated to composer, doesn't coming last branch

**Comment by IaraCanan** [comment]
how can I solve this issue, I'm having the same problem?
