### ISSUE TITLE
Suggestion with getPermissions()

### ISSUE THREAD

**Issue by subdesign** [kodeine/laravel-acl#25]
Imagine the following in the admin area. I want to edit a role's permissions, and when I use getPermission() helper function, I get all the permissions listed in arrays (rendered to list items here):
```
Administrator
create - 1
view - 1
update - 1
view.phone - 1
delete - 1
create - 1
update - 1
status - 1
delete - 1
edit - 1
```
as you see, because the function doesn't tell me what is the permission name, only the slugs are visible, how to decide to change for example the article's __create__ permission to 0, and not the user's permission ?
What if the getPermissions() can give back a bit complex array, starting with the permission name?
If you say no, then what is the purpose adding the name for a permission?

So, in theory:
```
['users'] => [
    'create' => 1,
    'edit' => 1,
    '...' => ...
],
['articles'] => [
    'create => 0,
    'edit' => 1,
    '...' => ...
]
```

**Comment by kodeine** [comment]
@subdesign, it's suppose to work like you mentioned, let me take a look in an hour

**Comment by subdesign** [comment]
Sorry my fault. Somehow my foreach loops hide the keys... :/
