### ISSUE TITLE
version 2.0.4 not getting installed from composer

### ISSUE THREAD

**Issue by erne85** [kodeine/laravel-acl#252]
The requested package kodeine/laravel-acl ^2.0.4 exists as kodeine/laravel-acl[1.0.0, 1.0.x-dev, 2.0.0, 2.0.1, 2.0.2, 2.0.3, dev-master, dev-revert-216-1.0, v0.1.0, v0.1.1, v0.1.2, v0.1.3] but these are rejected by your constraint.

**Comment by kodeine** [comment]
@erne85 can you please submit PR

**Comment by erne85** [comment]
> @erne85 can you please submit PR

@kodeine sorry, don't know what you mean, first time submitting issue
