### ISSUE TITLE
Question: Protect Methods

### ISSUE THREAD

**Issue by ssssteve** [kodeine/laravel-acl#26]
Hi @kodeine,

Is there a way to globally change the Protect Methods, or do we have to feed a modified array in via each route?

Your Protect Methods are currently set up as 

```php
[
   'create' => ['store'],    // protects store() method on create.user (create.alias)
   'view'   => ['index', 'create', 'show', 'edit'],     // protects index(), create(), show(), edit() methods on view.user permission.
   'update' => ['update'],
   'delete' => ['destroy']
]
```

However, these mean that users who are denied the permission to `store` and `update` can still access the _Create New Resource_ and _Update Resource_ pages, as their permissions for `create` and `edit` routes are bundled under `view`. I'd like to use the following:

```php
[
   'create' => ['create', 'store'],    // can create a new resource
   'view'   => ['index'],              // can see the resource
   'update' => ['edit', 'update'],     // can edit an existing resource
   'delete' => ['show', 'destroy']     // can delete a resource
]
```

Your Middleware class `HasPermission` has `protected $crud`; is there any chance this could be overridden via a `resources` array in config?

**Comment by kodeine** [comment]
@ssssteve, I'll push updates in an hour :)

**Comment by kodeine** [comment]
@ssssteve, please try now, you can use config now.
```php
return [
    'role'       => 'Kodeine\Acl\Models\Eloquent\Role',
    'permission' => 'Kodeine\Acl\Models\Eloquent\Permission',
    'crud'       => [
        'resource' => [....],
    ],
];
```

if config does not have crud.resource it will use the defaults. (i updated the defaults too).

**Comment by ssssteve** [comment]
Yup, that's fixed it nicely. :thumbsup: Thanks for the speedy update @kodeine! :star::star::star::star::star:

**Comment by kodeine** [comment]
You're welcome :)
