### ISSUE TITLE
Create Permissions

### ISSUE THREAD

**Issue by mbalcaen** [kodeine/laravel-acl#28]
Hello,

When I want to create a new permission with the example in the wiki, I'm getting this error: 
ErrorException in helpers.php line 686:
preg_replace(): Parameter mismatch, pattern is a string while replacement is an array.

Is this my mistake or an issue in the code?

Thanks!

Example:
$permission = new Permission();
$permUser = $permission->create([ 
    'name'        => 'user',
    'slug'        => [
        'create'     => true,
        'view'       => true,
        'update'     => true,
        'delete'     => true,
        'view.phone' => true
    ],
    'description' => 'manage user permissions'
]);

**Comment by kodeine** [comment]
Hello @mbalcaen, i was able to run the same example you gave and it works well, no errors. Kindly look at your other code. Or paste whole file.

Thank you

**Comment by mbalcaen** [comment]
Very strange...
![schermafbeelding 2015-03-22 om 11 39 30](https://cloud.githubusercontent.com/assets/1210283/6768995/29762a6a-d088-11e4-95d3-d04ec2995776.png)
![schermafbeelding 2015-03-22 om 11 40 11](https://cloud.githubusercontent.com/assets/1210283/6768998/445774a6-d088-11e4-9cf4-cb7171cf8262.png)

**Comment by kodeine** [comment]
@mbalcaen 
Looks like you are using your own permission model. Have you extended your model with laravel-acls and redefined in acl config?

Else you need to use like
```
use Kodeine\Acl\Models\Eloquent\Permission;
```

**Comment by mbalcaen** [comment]
Problem solved, I forgot to change the config file. Sorry!!

Do you guys have some suggestions for building a page to set permissions for a certain role?
I want to build something like the permissions page in Drupal. Now I'm struggling to create a permission from checkboxes. Tnx!

**Comment by kodeine** [comment]
@Mythos, is working on that i guess, you can ask him for help once he's done.

**Comment by martynbiz** [comment]
I have the same error but don't understand how this issue was solved. After migrations, I had created my own models (as instructed in the installation guide). I have added the package to your application service providers in config/app.php. And, I have published only to create the config/acl.php file, but I haven't edited this file as I wasn't instructed to do so. It would seem that roles are being created without a glitch, but permissions throw the same error as above:

```php
ErrorException in helpers.php line 703: preg_replace(): Parameter mismatch, pattern is a string while replacement is an array
```

You can see my models for Role and Permission below (pretty basic):

```php
<?php namespace App;

class Role extends Model {
    protected $fillable = ['name', 'slug', 'description'];
}
```

```php
<?php namespace App;

class Permission extends Model {
    protected $fillable = ['name', 'slug', 'description'];
}
```

And below is the code I'm running:

```php
$adminUser = User::create(array(
		'name' => 'Martyn Admin',
		'email' => 'martynbissett+admin@yahoo.co.uk',
		'password' => '$2y$10$DC7VS3vKu8VyctiB.eCx3Or05TND7bW1esayZSfeJa.Sx0MKKDtvW',
));

$moderatorUser = User::create(array(
		'name' => 'Martyn Moderator',
		'email' => 'martynbissett+moderator@yahoo.co.uk',
		'password' => '$2y$10$DC7VS3vKu8VyctiB.eCx3Or05TND7bW1esayZSfeJa.Sx0MKKDtvW',
));

// create roles

// admin
$roleAdmin = Role::create([
		'name' => 'Administrator',
		'slug' => 'administrator',
		'description' => 'Manage administration privileges'
]);

// moderator
$roleModerator = Role::create([
		'name' => 'Moderator',
		'slug' => 'moderator',
		'description' => 'Manage moderator privileges'
]);

// create permissions

// post listing -- error!
$permListing = Permission::create([
		'name'        => 'listing',
		'slug'        => [          // pass an array of permissions.
				'create'     => true,
				'view'       => true,
				'update'     => true,
				'delete'     => true,
				'view.phone' => true,
		],
		'description' => 'manage listing permissions'
]);

// assign permissions to roles

$roleAdmin->assignPermission($permListing);

// assign roles to users

$adminUser->assignRole($roleAdmin);
$moderatorUser->assignRole($roleModerator);
```
Anyway, other than that above the library looks really promising. Thanks

**Comment by kodeine** [comment]
@martynbiz 
Since you are using custom role and permission models, you need to define those in the config/acl.php as well.

**Comment by martynbiz** [comment]
Hi, thanks for the response. I tried doing that before from the previous posters issue, but perhaps I'm not doing it correctly. Here is the current changes I've made as I extended your Role and Permission models:

```php
<?php namespace App;

use Kodeine\Acl\Models\Eloquent\Role as AclRole;

class Role extends AclRole {
}
```

```php
<?php namespace App;

use Kodeine\Acl\Models\Eloquent\Permission as AclPermission;

class Role extends AclPermission {
}
```

And, I also updated the config/acl.php file - is this correct?

```php
<?php

return [
    // 'role'       => 'Kodeine\Acl\Models\Eloquent\Role',
    // 'permission' => 'Kodeine\Acl\Models\Eloquent\Permission',
    'role'       => 'App\Role',
    'permission' => 'App\Permission',
];
```

...but still I just get the same error. By the way, I can confirm too that I am using Laravel 5.0.

**Comment by martynbiz** [comment]
@kodeine 
Did I define them correctly in my example above? Is this how the provider expects the Role/Permission models to be defined/configured when they are my own?

**Comment by kodeine** [comment]
@martynbiz
Yes that seems right, are you using branch 1.0?
