### ISSUE TITLE
Middleware Parameters

### ISSUE THREAD

**Issue by mybigman** [kodeine/laravel-acl#29]
Hi Kodeine,

I came up with https://laracasts.com/discuss/channels/general-discussion/middleware-parameters-indirectly today...

There might be away of integrating this into your package... If I get time I shall have a look or you can :)

Thanks.

PS Keep up the awesome work mate.

**Comment by kodeine** [comment]
@mybigman,
Sure, let me know what you come up with and ill do the same.

**Comment by RomainLanz** [comment]
Closed due to inactivity.
