### ISSUE TITLE
Specified role id does not exists

### ISSUE THREAD

**Issue by luisvbz** [kodeine/laravel-acl#3]
Specified role id does not exists

Thank you for you help.

**Comment by kodeine** [comment]
@luisvbz please post code so I can take a look.

**Comment by luisvbz** [comment]
The above error was my fault , just presenting me this error " Specified role id does not exists " thanks for replying

**Comment by kodeine** [comment]
@luisvbz np, I will push commit in like 30 minutes. On my way to home :)

**Comment by mikhi** [comment]
Hi kodeine.

I have the issue. The error looks like this:
InvalidArgumentException in HasRole.php line 158:
Specified role id does not exists.

Here is the code:
$user->syncRoles('administrator'); or $user->assignRole([1,2,3]);

**Comment by kodeine** [comment]
@mikhi @luisvbz Please run composer update and test again, i've pushed some updates.

**Comment by mikhi** [comment]
Now it working.
Thank you for you help!

**Comment by kodeine** [comment]
@mikhi great.
