### ISSUE TITLE
Can't understand how to use protect_methods

### ISSUE THREAD

**Issue by MarcoROG** [kodeine/laravel-acl#30]
Hello, i have a really stupid question, but i can't understand how this works
I have seen you can protect methods based on permission in this way:
['protect_alias'  => 'user', 
'protect_methods' => [
        'create' => ['someMethod', 'anotherMethod'],
        'read'   => ['readMethod', 'showMethod'],
        'view'   => ['readMethod', 'showMethod'], // its same as read.
        'update' => ['editMethod'],
        'delete' => ['destroyMethod']
]];
But i cannot understand where i should put this array, it would make sense to put it into the controller i want to protect but it should be assigned to a variable. Assigning it to a single route doesn't make sense to me, is it specific for a route::resource?
Thanks a lot

**Comment by kodeine** [comment]
@MarcoROG,
There is no such thing as a stupid question.
`protect_methods` param is to be used in your routes. Does your controller use method names like create, store, show ... ?
If so then you dont need to use `protect_methods` param. You can simply use `'protect_alias' => 'user'` and your route will be protected by permissions *.user.

**Comment by MarcoROG** [comment]
Oh i see, so it is meant to be used on a route group for example.
If for example i want a more "granular" control over permissions i can still put a 'can' tag on each route right? Or this isn't a best practise?

**Comment by kodeine** [comment]
If for example you have a permission, `view.dashboard` you can use `can('view.dashboard)'` and then in protect_alias u can check for crud permission of *.user

**Comment by MarcoROG** [comment]
Oh i see, thanks a lot!
