### ISSUE TITLE
[Possible bug] Problem with multiple roles

### ISSUE THREAD

**Issue by MarcoROG** [kodeine/laravel-acl#31]
#Problem
I have just noticed something that doesn't look quite right to me, i have the following situation:
An user has two roles: student and secretary both have a different kind of permission regarding users obtained via permission inheritance:
```PHP
$genericUser=Permission::create([
            'name' => 'users',
            'slug' => [
                'create' => false,
                'view' => true,
                'update' => false,
                'approve' => false,
                'delete' => false,
            ],
            'description' => 'generic permission regarding users'
        ]);
        $secretaryUser = Permission::create([
            'name' => 'users.secretary',
            'slug' => [
                'create' => true,
                'edit' => true,
                'approve' => true,
                'delete' => true,
            ],
            'inherit_id' => $genericUser->getKey(),
            'description' => 'secretary permission regarding users'
        ]);
```
Since the user has both roles, it has both the permission users and users.secretary.
The problem is that when i call can('edit.users') it returns false, if i call $user->getPermissions() i get the permissions of the last role assigned to the user (if i assign the generic first, i get the permissions of the secretary and vice versa).

#Where the issue is
I think that depends on the fact that the method 'can' in 'HasPermission' trait calls the method 'getPermissions' which uses an array_replace_recursive, which replaces the permission set with the latest extracted from the database and not the higher in clearance

#Proposal
When the user has more roles, each one with a different permission regarding the same thing, they should be merged granting the highest level of clearence, for example
```PHP
User has role1 and role2
role1 has permission1:
'name' => 'generic'
 'slug' => [
                'create' => true,
                'edit' => false,
            ],
role2 has permission2:
'name' => 'generic'
 'slug' => [
                'create' => false,
                'edit' => true,
            ],
```
Calling getPermissions() on him should return
```PHP
"users"=>array:2[
"create"=>"true"
"edit"=>"true"
]
```

#Workaround
array_replace_recursive overwrites everything previously existing, even if this means loosing some clearence, to avoid that we need to check for every key that it's value is higher than the one we currently have, i can't find any fancy function in PHP to do this:
```PHP
foreach($this->roles as $role){
  foreach($role->getPermissions() as $slug=>$array){
    if(array_key_exists($slug,$permissions){
      foreach($array as $clearence=>$value){
       !$value?:$permissions[$slug][$clearance]=true;
     }
   }else{
      $permissions = array_merge($permissions,array($slug => $array));
   }
 }
}
```
It's quite an ugly piece of code and i'm sorry for that, maybe you can come up with something better.
Sorry for my horrible english

**Comment by kodeine** [comment]
@MarcoROG 
can you try dev-dev branch, it should be solved in that since dev branch uses ntfs (more permissive permission wins). please try that and let me know if that works.

**Comment by MarcoROG** [comment]
The foreach in the getPermissions method is still using the same array_replace_recursive method, so i think the outcome will be the same, let me try and i'll tell you

**Comment by kodeine** [comment]
@MarcoROG 

This is what i get when i do `getPermissions();`

```php
array:1 [
  "users" => array:6 [
    "create" => true
    "view" => true
    "update" => false
    "approve" => true
    "delete" => true
    "edit" => true
  ]
]
```

Following were the `permissions` i used and both attached to a role `admin`.

```php
        $genericUser=Permission::create([
            'name' => 'users',
            'slug' => [
                'create' => false,
                'view' => true,
                'update' => false,
                'approve' => false,
                'delete' => false,
            ],
            'description' => 'generic permission regarding users'
        ]);
        $secretaryUser = Permission::create([
            'name' => 'users.secretary',
            'slug' => [
                'create' => true,
                'edit' => true,
                'approve' => true,
                'delete' => true,
            ],
            'inherit_id' => $genericUser->getKey(),
            'description' => 'secretary permission regarding users'
        ]);
```

**Comment by MarcoROG** [comment]
Well the problem is that you attached both of them to the role 'admin', try attaching them to two different roles, and assign those two roles to the same users, and you'll see the problem

**Comment by kodeine** [comment]
@MarcoROG 
Got it... will review and push updates asap. :+1:

**Comment by MarcoROG** [comment]
okok thanks a lot again for all your hard work!

**Comment by kodeine** [comment]
@MarcoROG 
please try the dev branch.

**Comment by MarcoROG** [comment]
okok it seems to work fine now

**Comment by kodeine** [comment]
@MarcoROG, lovely, sorry i couldnt use your PR since it had syntax error. Should i merge it with master? or should we wait few days until we found some more bugs? :D

**Comment by MarcoROG** [comment]
I'd wait a couple of days to see if someone finds some kind of bug.
No problem for the PR, i was writing it with my mobile phone in class so i made a lot of errors, the important thing is that you got what i meant and now it works
