### ISSUE TITLE
Use middleware ?

### ISSUE THREAD

**Issue by Rtransat** [kodeine/laravel-acl#37]
Hi,

I've some issues with the middleware. You can see my seed:

```php
<?php

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class UsersTableSeeder extends Seeder {

	public function run()
	{
		DB::table('users')->truncate();

		$admin = new \App\User();
		$admin->email = "admin@admin.com";
		$admin->password = "admin";
		$admin->save();

		$editor = new \App\User();
		$editor->email = "editor@editor.com";
		$editor->password = "editor";
		$editor->save();

		$user = new \App\User();
		$user->email = "user@user.com";
		$user->password = "user";
		$user->save();
	}

}
```

```php
<?php

use App\User;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Kodeine\Acl\Models\Eloquent\Permission;
use Kodeine\Acl\Models\Eloquent\Role;

class AclTableSeeder extends Seeder {

	public function run()
	{

		DB::table('roles')->truncate();
		DB::table('role_user')->truncate();
		DB::table('permissions')->truncate();
		DB::table('permission_role')->truncate();
		DB::table('permission_user')->truncate();

		$roleAdmin = new Role();
		$roleAdmin->name = 'Administrator';
		$roleAdmin->slug = 'admin';
		$roleAdmin->description = 'manage administration privileges';
		$roleAdmin->save();

		$roleEditor = new Role();
		$roleEditor = $roleEditor->create([
			'name' => 'Editor',
			'slug' => 'editor',
			'description' => 'manage editor privileges'
		]);

		$roleUser = new Role();
		$roleUser = $roleUser->create([
			'name' => 'User',
			'slug' => 'user',
			'description' => 'manage user privileges'
		]);


		$userAdmin = User::where('email', '=', 'admin@admin.com')->first();
		$userAdmin->assignRole($roleAdmin);

		$userEditor = User::where('email', '=', 'editor@editor.com')->first();
		$userEditor->assignRole($roleEditor);

		$userUser = User::where('email', '=', 'user@user.com')->first();
		$userUser->assignRole($roleUser);


		$permissionRole = Permission::create([
			'name'        => 'role',
			'slug'        => [ // an array of permissions.
				'index' => true, // with or without it doesn't work
				'create' => true,
				'view'   => true,
				'update' => true,
				'delete' => true,
			],
			'description' => 'manage role'
		]);

		$permissionUser = Permission::create([
			'name'        => 'role.editor',
			'slug'        => [ // an array of permissions only for student
				'create' => false,
			],
			// we use permission inheriting.
			'inherit_id' => $permissionRole->getKey(),
			'description' => 'user roles permissions'
		]);

		$roleAdmin->assignPermission('role');
		$roleEditor->assignPermission('role.editor');
	}

}
```

If I'm logged as admin I see with $user->getPermissions():
```
"role" => array:4 [▼
    "create" => true
    "view" => true
    "update" => true
    "delete" => true
  ]
```

And as editor:
```
"role" => array:4 [▼
    "create" => false
    "view" => true
    "update" => true
    "delete" => true
  ]
```

And in my routes.php
```php
Route::group( [
	'middleware' => ['auth', 'acl'],
	'is' => 'admin|editor',
	'can' => 'create.role',
    ], function () {

	Route::resource('roles', 'RolesController');

});
```

So, as admin it's working great, but as editor, if I try to go in /roles, I'm not authorized to see that page and I don't know what I'm doing wrong.

I would like to check if the user is admin or editor and check if he can create a role only. Editor is allowed to views the /roles pages.

The solution is to create each route for a resource but it's really heavy to write each RESTFUL resource like this:
```php
Route::get('/roles', [
	'uses'        => 'RolesController@index',
	'middleware'   => ['auth', 'acl'],
	'is'           => 'admin|editor']);

Route::get('/roles/create', [
	'as' => 'roles.create',
	'uses'        => 'RolesController@create',
	'middleware'   => ['auth', 'acl'],
	'is'           => 'admin|editor',
	'can' => 'create.role']);
```

Or If I want to use resource I need to update your middleware and it's working otherwise I'm never in the condition. I need to update my database to add ```"store": true``` for role and ```"store": false``` for role.editor and of course in routes.php I have ```'can' => 'store.role'```:
```php
if ( $this->protectMethods() ) {
    return $next($request);
}
```

I think it's because of ```last(array_keys($crud)) . '.' . $this->parseAlias();``` You get the last key:

When I'm on /roles/create route:
```
$crud = array_where($methods, function ($k, $v) use ($called) {
    return in_array($called, $v);
});
dd($crud);

array:2 [▼
  "create" => array:2 [▼
    0 => "create"
    1 => "store"
  ]
  "store" => array:2 [▼
    0 => "create"
    1 => "store"
  ]
]

$permission = last(array_keys($crud)) . '.' . $this->parseAlias();
dd($permission);

'store.role'
```

It looks we can't never check the create method because of that.

PS: Sorry for my english

Thx.

**Comment by kodeine** [comment]
@Rtransat 
i will try this at my machine and get back to you.

**Comment by kodeine** [comment]
@Rtransat 
Are you using master branch or dev-dev?

**Comment by Rtransat** [comment]
I'm using dev-master in my composer.json but I have the master I think because in the config/acl.php I can't see the ntfs key.

**Comment by Rtransat** [comment]
Now, if I ```dump($this->auth->user()->getPermissions());``` as admin and editor I have:

```
array:1 [▼
  "role" => array:4 [▼
    "create" => true
    "view" => true
    "update" => true
    "delete" => true
  ]
]
```

create should be false for editor. And of course as admin or editor /roles, /roles/create working for both.

**Comment by kodeine** [comment]
@Rtransat 
I tried the same code you pasted here at my machine and it seems to work fine as it should.

by simply using `'can' => 'create.role',` on a `route::resource()` (like you did) will check for permission `create.role` no matter what resource url it is. so editor has permission denied on index because it checks for create.role permission first.

Since you want to protect resource, please try this.

```php
Route::group( [
    'middleware' => ['auth', 'acl'],
    'is' => 'admin|editor',
    //'can' => 'create.role',
    'protect_alias' => 'role',
], function () {
    Route::resource('/', 'WelcomeController');
});
```
`'protect_alias' => 'role'` will protect your CRUD resource methods by checking needed permission for *.role. (based on route)

**Comment by Rtransat** [comment]
I think I have already try with protect_alias and removing "can" but I'll try tomorrow. Did you see my screen with dev-dev branch the getPermissions methods return true for each crud method, admin and editor. It's weird ?

**Comment by kodeine** [comment]
@Rtransat
I tried your code on dev-dev and editor had create=false.

**Comment by Rtransat** [comment]
Still the same problem :/. With phpmyadmin I can see role.editor with create to false but if I debug $this->auth->user()->getPermissions(); admin and editor has the same permissions, true for create, view, update, delete.

And with 'protect_alias' => 'role', same problem again :/. Admin can view /roles but /roles/create it's the 401 error.

**Comment by kodeine** [comment]
Possible to give me your Skype?
I'll help you out easily.

On Thursday, April 9, 2015, Rtransat <notifications@github.com> wrote:

> Still the same problem :/. With phpmyadmin I can see role.editor with
> create to false but if I debug $this->auth->user()->getPermissions(); admin
> and editor has the same permissions, true for create, view, update, delete.
>
> And with 'protect_alias' => 'role', same problem again :/. Admin can view
> /roles but /roles/create it's the 401 error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/kodeine/laravel-acl/issues/37#issuecomment-91249883>.
>


-- 
Best Regards,

Ahsen Masood.
Founder President.
SaveLife Foundation.
www.savelife.pk <http://www.savelife.pk/about.php>

**Comment by Rtransat** [comment]
@kodeine it seems to work great :)
