### ISSUE TITLE
[Suggestion]Soft deletes on pivot tables

### ISSUE THREAD

**Issue by MarcoROG** [kodeine/laravel-acl#4]
First of all thanks for this awesome repo.
I'd like to use this system to create a webapp dedicated to the management of a school.
The key is that many users will have temporary roles, and i should be able to keep track of them.

To do so, the most logic way is to introduce soft deletes on the pivot tables users_roles and user_permissions, so that, by using created_at and deleted_at you can detect how much an user has been in charge of a given role.

It'd be awesome if you could implement that since not all roles are persistent.

**Comment by kodeine** [comment]
@MarcoROG alright, ill work on that too. If that's an urgent require you can extend the models and use soft deletes.

**Comment by MarcoROG** [comment]
I have a very long deadline so no hurry.
I think it'd be a good addition tho, so you can keep track of roles assignment
Thanks for all you're doing

**Comment by kodeine** [comment]
@MarcoROG no problem bud.

**Comment by MarcoROG** [comment]
I Was thinking about adding implementing it this way:
-daleted_at field in user_roles
-when querying for roles in the many-many relationship, adding a parameter to select withTrashed, onlyTrashed or normal
-when revoking roles, using the soft delete instead of detatch
-Not sure about this: adding an option 'was' which calls a 'was' method that works exactly like 'is' but calling getRoles with onlyTrashed.

I'll start my Easter break on wednesday and i'll be able to contribute, for now i can just prototype and write down some ideas since i have a lot of exams

**Comment by kodeine** [comment]
@MarcoROG 
sounds good man, feel free to send a PR.

**Comment by kodeine** [comment]
@MarcoROG hows the progress :)

**Comment by MarcoROG** [comment]
hey, can we have a private chat? like skype maybe

**Comment by kodeine** [comment]
sure, add http://pastebin.com/df0upvkQ
