### ISSUE TITLE
Validating Role using operator vs pipe inconsistency

### ISSUE THREAD

**Issue by RhythmScout** [kodeine/laravel-acl#40]
`Auth::user()->is('manager'); // TRUE`
`Auth::user()->is('admin|manager'); // TRUE`
`Auth::user()->is(['admin','manager'], 'or'); // FALSE`

First 2 cases are correct - The user is assigned the manager role.
Shouldn't the 3rd case be returning TRUE as well?

**Comment by RhythmScout** [comment]
One additional note... I only have data in users, roles, role_user tables at this point. No entries in permissions, permission_role, or permission_users table yet.

**Comment by kodeine** [comment]
@RhythmScout 
Can you please paste your models, so i can use them locally and see whats going on.

**Comment by RhythmScout** [comment]
User.php:
`
<?php namespace App\Models;

use Auth;
use Kodeine\Acl\Traits\HasRole;
use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Collection;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

class User extends BaseModel implements AuthenticatableContract, CanResetPasswordContract {

	use Authenticatable, CanResetPassword, HasRole;

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'users';


	/**
	 * The attributes that are mass assignable.
	 *
	 * @var array
	 */
	protected $fillable = ['name', 'email', 'password'];


	/**
	 * The attributes excluded from the model's JSON form.
	 *
	 * @var array
	 */
	protected $hidden = ['password', 'remember_token'];


    /*
    | START Relationships
    */

    /**
     * belongsToMany('Client')
     */
    public function clients()
    {
        return $this->belongsToMany('App\Models\Client');
    }

    /*
    | END Relationships
    */


    /**
     * Call the appropriate method to find all entities
     * limited by the Auth::user's Role
     *
     * @param array $with
     *
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function getAllForCurrentRole(array $with = [])
    {
        debug(Auth::user()->is('manager'));
        debug(Auth::user()->is('admin|manager'));
        debug(Auth::user()->is(['admin','manager'], 'or'));

        if (Auth::user()->is('admin|manager')) {
            return $this->getAllForAdmin($with);
        }

        return new Collection();
    }


    public function getAllForAdmin($with = [])
    {
        return $this->getAll($with);
    }
}
`

Role.php:
`
<?php namespace App\Models;

use Kodeine\Acl\Models\Eloquent\Role as ACL_Role;

class Role extends ACL_Role {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'roles';

}
`

Permission.php:
`
<?php namespace App\Models;

use Kodeine\Acl\Models\Eloquent\Role as ACL_Permission;

class Permission extends ACL_Permission {

	/**
	 * The database table used by the model.
	 *
	 * @var string
	 */
	protected $table = 'permissions';

}
`

config/acl.php:
`
<?php

return [

    'role'       => 'App\Models\Role',
    'permission' => 'App\Models\Permission',
//    'role'       => 'Kodeine\Acl\Models\Eloquent\Role',
//    'permission' => 'Kodeine\Acl\Models\Eloquent\Permission',

    'ntfs'       => true,
];

`

Please let me know if you need anything else.

**Comment by RhythmScout** [comment]
BaseModel.php:
`<?php namespace App\Models;

use Illuminate\Database\Eloquent\Model;

abstract class BaseModel extends Model {

    /**
     * Find all entities
     *
     * @param array $with
     *
     * @return Illuminate\Database\Eloquent\Collection
     */
    public function getAll(array $with = [])
    {
        return $this::with($with)->get();
    }
}
`

**Comment by RhythmScout** [comment]
Could the problem possibly be line 60 of HasRole.php?

```$operator = is_null(null) ? $this->parseOperator($slug) : $operator;```
Should be:
```$operator = is_null($operator) ? $this->parseOperator($slug) : $operator;```

I made this swap and seems to be working properly now...

**Comment by kodeine** [comment]
@RhythmScout 
That was a bug which was fixed in recent commits. Please make sure you are using latest version, run composer update

**Comment by RhythmScout** [comment]
@kodeine I apologize if I'm doing something wrong here, but I continue to see the `$operator = is_null(null) ?....` code in the master brach:

https://github.com/kodeine/laravel-acl/blob/master/src/Kodeine/Acl/Traits/HasRole.php

I am using "kodeine/laravel-acl": "dev-master" in my composer.json as well.

**Comment by kodeine** [comment]
@RhythmScout 
Hmm, weird that commit wasnt updated. Let me push it now. Thanks for finding it out.

**Comment by RhythmScout** [comment]
Happy to help....and thanks for a great package.
