### ISSUE TITLE
Permissions based on relationships

### ISSUE THREAD

**Issue by angelocala94** [kodeine/laravel-acl#41]
It's possible to have permission based on relationships automatically?
For example, if i have two tables: users and posts.
Can i assign a permission to user A that allow him to see only own posts?
Or i need to do it manually?

**Comment by RomainLanz** [comment]
For the moment you need to do it manually. On our v2 this would be handle automatically!

**Comment by angelocala94** [comment]
When will be released?

**Comment by RomainLanz** [comment]
The v2 will be stable and release at the end of august.

**Comment by angelocala94** [comment]
Perfect :)
