### ISSUE TITLE
Reduce number of query and prevent duplicates

### ISSUE THREAD

**Issue by billmn** [kodeine/laravel-acl#43]
Hi,
I'm testing your package and I have followed you guide.

In a controller I have used this:
```php
dump($this->logged->can('view.user'));
dump($this->logged->can('create.user'));
dump($this->logged->can('update.user'));
dump($this->logged->can('delete.user'));
dump($this->logged->can('view.post'));
dump($this->logged->can('create.post'));
dump($this->logged->can('update.post'));
dump($this->logged->can('delete.post'));
```

and I notice that it produce a lot of query which increase according to the number of check I do.
Most of this query are duplicated.

![schermata 2015-05-08 alle 09 48 34](https://cloud.githubusercontent.com/assets/779534/7532560/992f4062-f568-11e4-9edf-a1f676068730.png)

I think it's important to reduce the number of query and prevent any duplicate.
Do you have any idea why this happens?

**Comment by kodeine** [comment]
@billmn
you can simply use 
```php
dump($this->logged->can('view.user|create.user|delete.post....'));
```
where | (pipe) represents the OR operator, if you use ,(comma) it will represent as AND operator.

Let me know if that works, i am still working on its caching system. so hopefully i'll be done soon.

**Comment by billmn** [comment]
Yep for sure...

My example is only to highlight that if a developer needs to use the "can" method in different parts of an application, the package makes a lot of query. 

I think also that is important to prevent any duplicated query. 

Thank you for your work

**Comment by kodeine** [comment]
@billmn, ill be updating it soon with cache capabilities.

**Comment by billmn** [comment]
Really appreciated, thank you!
