### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by mjcombalicer** [kodeine/laravel-acl#44]
I'm not sure if I missed this but what does "Prefix" do in protecting routes?

Basically I'm trying to figure out why I'm getting 404 with it and getting the page/authorisation error once that is removed.

Thanks

**Comment by kodeine** [comment]
@mjcombalicer 
so for example you have a permission alias of `user`. In routes you can set prefix of `user` so route will check all read/write `user` permissions eg, it will check `create.user`, 'view.user' etc.

**Comment by RomainLanz** [comment]
Closed due to inactivity.
