### ISSUE TITLE
Help: Solution for segmented group of roles

### ISSUE THREAD

**Issue by nerijunior** [kodeine/laravel-acl#47]
Hello! I'm developing one ERP and I'm looking a solution for:
- Users can control more than one companies.
- **Users have different permissions for the company branches.**

Example: John Doe is employee from two companies A and B on A he have permission to delete users on B not.

So he need to have two different roles and permission on the same user.

What's the best way to solve this?

Thanks!

**Comment by kodeine** [comment]
@nerijunior 

take a look at this post #12 it will give you some ideas.
