### ISSUE TITLE
Middleware inside resource controller

### ISSUE THREAD

**Issue by angelocala94** [kodeine/laravel-acl#49]
I've tried to do this inside my resource controller:
```php
public function __construct(){
    $this->middleware('auth');
    $this->middleware('acl', ['protect_alias' => 'salon']);
}
```
but it doesn't work, why?

**Comment by kodeine** [comment]
@angelocala94 

you cannot pass params to middleware in controllers.
you can simply use protect_alias in your routes.

**Comment by angelocala94** [comment]
There is a way to use the resource URL automatically as protect_alias?

**Comment by kodeine** [comment]
@angelocala94 
You can make a middleware or a function which will detect route and returns its protect_alias.

**Comment by angelocala94** [comment]
Yep, i've extended your middleware, thanks.
