### ISSUE TITLE
How to validate multiple roles using and/or operators

### ISSUE THREAD

**Issue by mybigman** [kodeine/laravel-acl#5]
Hi,

Can I do this...

```
'is' => 'admin|mod'
```

So if the user is an 'admin' OR 'moderator' they can access...

and also...

```
'is' => 'mod.editor'
```

So if the user is a 'moderator' AND 'editor' they can access...

**Comment by kodeine** [comment]
@mybigman, yes you can do `'is' => 'admin|mod'` where `admin` and `mod` are Roles.
for permissions, you need to use `'can' => 'editor.mod'` where `editor` is a permission and `mod` is an alias. basically we bind multiple permissions to an alias. 

to create new permission `editor.mod`, you would have to do 
```php
$permission = new Permission();
$editor = $permission->create([ 
    'name'        => 'mod', // alias
    'slug'        => [          // pass an array of permissions.
        'editor'     => true
    ]
]);

//or slug without array.

$editor = $permission->create([ 
    'name'        => 'mod', // alias
    'slug'        => 'editor' // it will be considered as editor => true.
]);
```

Lets assign the newly created permission to `mod` role.

```php
$roleMod = Role::first();
$roleMod->assignPermission($editor);
```

Now you can validate permissions

```php
$user->canEditorMod();
//or
$user->can('editor.mod'); 
```

**Comment by mybigman** [comment]
@kodeine you champ :)

**Comment by kodeine** [comment]
@mybigman should we have a different symbol for AND operator instead of a dot.
Dot might confuse people with permission aliases.

**Comment by mybigman** [comment]
@kodeine sounds great.

**Comment by kodeine** [comment]
@mybigman, please try the dev branch. It supports operators in is() and can() methods. Once you give me a go, ill merge it to master.

**Comment by kodeine** [comment]
Merged to master.
