### ISSUE TITLE
__call() default value causes an error with Mockery

### ISSUE THREAD

**Issue by wowzzangga** [kodeine/laravel-acl#51]
I'm attempting to mock a class with User Eloquent model which has the HasRole traits. When I run my test suite I get this error:
````
ErrorException: Declaration of Kodeine\Acl\Traits\HasRole::__call() should be compatible with Illuminate\Database\Eloquent\Model::__call($method, $parameters)
````
After a little bit of research, I found https://github.com/keenlabs/KeenClient-PHP/pull/52 could be related to this issue. It suggests `__call()`'s `$args` parameter is required and will always be present as an array and adding a default value can cause problems. It also references https://github.com/padraic/mockery/issues/263 which seems the same as mine.

**Comment by kodeine** [comment]
@wowzzangga 
so adding ```__cal($args)``` fixes the issue?

**Comment by wowzzangga** [comment]
@kodeine 
Yes, so please drop the default value for __call(), like this : 
`public function __call($method, $arguments)`

Thank you so much.

**Comment by kodeine** [comment]
@wowzzangga 
Issue solved. Thanks
