### ISSUE TITLE
Question: How does $request->user get the user?

### ISSUE THREAD

**Issue by isaackearl** [kodeine/laravel-acl#52]
This acl package looks amazing and so I've started implementing it in a project I'm working on.. my problem is that I want to use it a bit differently because I don't want to attach the roles and permissions to my App\User Model.  The reason for this is because in my application a user can authenticate using their user, but they have a different profile for each "company" that they register under.  

In other words I have another model called Gamer, that essentially works as my user model once a person is logged in to a certain company.  

I've gotten all of this to work properly using your package other then the Middleware.  When it calls $request->user() I get a null value and I'm not sure how it is trying to get that.  

this type of stuff works fine for me

```
$gamer->getRoles()
$gamer->is('admin');
```
etc... but the middleware doesn't try and get the correct user model... is there a place I can override that?

I always get this error because user is null: 
```
BadMethodCallException in HasPermission.php line 69:
Call to a member function is() on a non-object (NULL)
```

here is how I created my Model for Role (and permission) to override the users() function and use my gamers model
```
<?php namespace App;

use Kodeine\Acl\Models\Eloquent\Role as AclRole;

class Role extends AclRole
{


    /**
     * alias for gamers()
     *
     * @return Gamer
     */
    public function users()
    {
        return $this->gamers();
    }

    /**
     * Roles can belong to many gamers.
     *
     * @return Gamer
     */
    public function gamers()
    {
        return $this->belongsToMany('App\Gamer')->withTimestamps();
    }

}
```

I also updated the migrations etc.. so the only thing I can't figure out is the middleware.

**Comment by kodeine** [comment]
@isaackearl 
If you are using your custom user / role models, you can define them in config file.

```php
 'role'       => 'Kodeine\Acl\Models\Eloquent\Role',
 'permission' => 'Kodeine\Acl\Models\Eloquent\Permission',
```

**Comment by isaackearl** [comment]
@kodeine 

ya I've updated that my custom role and permission model are working great.  That isn't the problem.  I was just trying to add that to show you how I'm not using config(auth.model) to get the user model for the roles.  

basically the real question is why doesn't the middleware work for me.  it breaks when it does 
```
$request->user()->is($role)
```
because user is null.  I can't see any indication in the code of where it is trying to get the user from.

**Comment by isaackearl** [comment]
@kodeine ... nvm I'm realizing that $request->user() function actually exists on the request and it resolves the user somehow (haven't figured it out yet).  I guess I will come back and answer this question later for anybody else trying to use something other then their regular user model for roles and permissions...

**Comment by kodeine** [comment]
@isaackearl 
yeah $request->user() is from laravel. Logged in user. do write back the resolution :+1:

**Comment by isaackearl** [comment]
@kodeine I created my own middleware based on yours, that gets the user from my JWT Token (It's an API).  Here is a portion of my modified middleware.. instead of $request->user() I have a getUser() function that allows me to get it from my token.

```
  /**
     * Check if user has requested route role
     *
     * @return bool
     */
    protected function hasRole()
    {
        $role = $this->getAction('is');

        return ! $this->forbiddenRoute() && $this->getUser()->is($role);
    }

    /**
     * Check if user has requested route permissions
     *
     * @return bool
     */
    protected function hasPermission()
    {
        $do = $this->getAction('can');

        return ! $this->forbiddenRoute() && $this->getUser()->can($do);
    }


    /**
     * @return string
     */
    protected function getUser()
    {
        return JWTAuth::toUser();
    }
```

**Comment by RomainLanz** [comment]
@isaackearl Can we close this?

**Comment by isaackearl** [comment]
@RomainLanz Yes.
