### ISSUE TITLE
Example of using this package with Laravel buil-in Auth system.

### ISSUE THREAD

**Issue by omar-faruk-sust** [kodeine/laravel-acl#53]
I am beginner of Laravel 5 even in Laravel too. So can you please give an example tutorial to working with laravel built-in Auth and registration system. i have modified the registration system of laravel and i install and cofigure your ACL package. but do not understand how i can add a role and permission.

**Comment by RomainLanz** [comment]
You can find all of that kind of information on [our wiki](https://github.com/kodeine/laravel-acl/wiki).
