### ISSUE TITLE
Call to a member function keyBy() on null

### ISSUE THREAD

**Issue by yasseralkahf** [kodeine/laravel-acl#55]
Hello, 

I created a new laravel project with new database, I did exactly what you did in the wiki, I hard coded a new user in the database, and then I tried to add a user permission like what you did

$user = User::first();
$user->addPermission('user');

And I get this error:

FatalErrorException in HasUserPermission.php line 17: Call to a member function keyBy() on null

Can you help please ?

**Comment by yasseralkahf** [comment]
Ah I get it, I thought that when I did $user->addPermission it will create a CRUD

**Comment by RomainLanz** [comment]
Hi @yasseralkahf,

Is it still an issue?

Have you also use `HasPermission` trait?

**Comment by yasseralkahf** [comment]
Hello @RomainLanz, 

THe issue was that I use HasUserPermission trait, instead of HasPermission, now when I use HasPermission, it works fine, thank you
