### ISSUE TITLE
ErrorException in HasRole.php line 79: in_array() expects parameter 2 to be array, object given

### ISSUE THREAD

**Issue by camiant** [kodeine/laravel-acl#56]
Please fix it for L5.1 compatibility

**Comment by kodeine** [comment]
@camiant
Can you cast the second param as array and test? If that works ill push commit

**Comment by camiant** [comment]
works like a charm :)

2015-06-09 23:52 GMT+02:00 Kodeine <notifications@github.com>:

**Comment by camiant** [comment]
sorry.. my mistake: I'm not recognized in my very role

2015-06-09 23:52 GMT+02:00 Kodeine <notifications@github.com>:

**Comment by camiant** [comment]
line 79 needs to be written as :

return in_array($slug, $roles->toArray());

2015-06-09 23:52 GMT+02:00 Kodeine <notifications@github.com>:

**Comment by kodeine** [comment]
@camiant 
i've pushed the commit. Let me know if that resolves the issue.

**Comment by kodeine** [comment]
Follow up at #60.
