### ISSUE TITLE
assigning Permission to user issue

### ISSUE THREAD

**Issue by yasseralkahf** [kodeine/laravel-acl#59]
Hello, 

I found an issue, that if you assign a permission to a user that already have that permission, it will retrun an exception said: 
UnexpectedValueException in compiled.php line 14223: The Response content must be a string or object implementing __toString(), "boolean" given.

I think it's because of the "return false;" that you add in the last of the function assignPermission in HasPermission trait.

**Comment by yasseralkahf** [comment]
The solution that I suggest that to make the return of assignPermission($permission) function in HasPermission.php equals 0. not "false"

**Comment by kodeine** [comment]
@yasseralkahf 
it should not assign the permission as it checks if permission id doesnt already exists.
Could you please provide code so i can run and debug?

Thank you.

**Comment by pawanmeshram** [comment]
Hello,
I followed the installation instruction and getting an error.
Class App\Http\Kodeine\Acl\Middleware\HasPermission does not exist
I am using laravel 5.1 version.

**Comment by CylonSK** [comment]
did you register middleware in kernel.php as is described in installation guide ?

Add the middleware to your `app/Http/Kernel.php`.
```php
protected $routeMiddleware = [

....
'acl' => 'Kodeine\Acl\Middleware\HasPermission',

];
```
