### ISSUE TITLE
is() fails on Laravel 5.1

### ISSUE THREAD

**Issue by xKairu** [kodeine/laravel-acl#62]
At first I had to put `->all()` onto the end of the `getRoles()` call to fix the `in_array()` issue, which worked. Decided to try updating to see if it was fixed, and it wasn't 100% fixed.

Dumping `getRoles()` returns this:

![2015-06-13_15-02-24](https://cloud.githubusercontent.com/assets/450516/8142765/724bb80e-11dd-11e5-9b91-d8986bfd37fa.png)

I had to fix it by doing: `$roles = array_values($this->getRoles())[0];`. This works, however now all my `is()` calls are broken because of the above screenshotted issue.

This seems to fix the issue entirely, within `hasRoles()`:

`array_values((array)$this->roles->lists('slug'))[0]`

I'd make a pull request but I don't know how, or even if this fix is ideal.

**Comment by kodeine** [comment]
@xkairu
Ill push an update tomorrow.
