### ISSUE TITLE
Protecting custom controller methods

### ISSUE THREAD

**Issue by parallelaus** [kodeine/laravel-acl#68]
Is there a way to protect controller methods that does not form part of the standard CRUD methods. 

In my example, I want to create a setStatus method in the controller and only allow certain users to set the status of the resource. So the normal update method will be available for some users, but they will not be able to set the resource status column via the update method. Then the setStatus method will be available for other users.

Great library! Really saving me a lot of time.

**Comment by kodeine** [comment]
@parallelaus yes you can take a look at [this](https://github.com/kodeine/laravel-acl/wiki/Protect-Routes#params-definitions).

**Comment by kodeine** [comment]
@parallelaus does it solve the problem? if so please close the issue.

**Comment by parallelaus** [comment]
Yes, thanks I figured it out. Maybe you can add a few more examples to the Wiki just to make it a bit clearer. 

All in all a great library and I am happy that we are building our application with this.

**Comment by parallelaus** [comment]
This is what I am doing:

permission table seeder:

		$permOrganisation = Permission::create([
			'name'	=> 'organisation',
			'slug'	=> [
				'create' => true,
				'view'   => true,
				'update' => true,
				'delete' => true,
				'view.billing-organisation' => true,
				'delete.billing-organisation' => true,
				'update.billing-organisation' => true,
				'view.owner' => true,
				'create.owner' => true,
				'delete.owner' => true,		
			],
			'description'	=> 'Manage Organisation'
		]);

role table seeder:

		$role = [
			'name' => 'System Admin User',
			'slug' => 'sys-admin',
			'description' => 'Administrate the system - Never assign to client user', 
		];
		$roleSysAdmin = Role::create($role);
                $roleSysAdmin->assignPermission('organisation');

routes.php:

// Basic CRUD Methods
Route::group(array('prefix' => 'v1', 'middleware' => ['auth','acl'], 'protect_alias' => 'organisation'), function() {
	// /organisation
	Route::resource('organisations', 'meta\OrganisationController', array('only' => array('index', 'store', 'show', 'update', 'destroy')));
});

// Custom methods
Route::group(array('prefix' => 'v1', 'middleware' => ['auth','acl']), function() {
	// /organisation/{organisation_id}/billing_organisation
	Route::get('organisation/{id}/billing_organisation', ['uses' => 'meta\OrganisationController@showParent', 'can' => 'view.billing-organisation.organisation']);
	Route::delete('organisation/{id}/billing_organisation', ['uses' => 'meta\OrganisationController@unsetParent', 'can' => 'delete.billing-organisation.organisation']);
	Route::put('organisation/{id}/billing_organisation/{billing_org_id}', ['uses' => 'meta\OrganisationController@setParent', 'can' => 'update.billing-organisation.organisation']);

         // organisation/{id}/owner
         Route::get('organisation/{id}/owner', ['uses' => 'meta\OrganisationController@showOwner', 'can' => 'view.owner.organisation']);
         Route::put('organisation/{id}/owner/{user_id}', ['uses' => 'meta\OrganisationController@assignOwner', 'can' => 'create.owner.organisation']);
        Route::delete('organisation/{id}/owner/{user_id}', ['uses' => 'meta\OrganisationController@removeOwner', 'can' => 'delete.owner.organisation']);
});

Hope this helps you.

**Comment by wdog** [comment]
thanks a lot for your code!!!!
so you are not using ```protect_methods```?
