### ISSUE TITLE
Middleware constructor

### ISSUE THREAD

**Issue by mybigman** [kodeine/laravel-acl#7]
Hi,

Not sure if this possible or not or im going about this the wrong way.

```
$this->middleware('acl', ['is' => 'admin']);
```

It never sees the "is"

Thanks

**Comment by kodeine** [comment]
I tried to find a way to do this but no luck, array is not passed to middleware, any thoughts?

**Comment by mybigman** [comment]
@kodeine I had a bit of a look last night doesnt seem possible without changing the core...

I might have another look.

Thanks.
