### ISSUE TITLE
require.kodeine/laravel-acl : unbound version constraints (dev-master) should be avoided

### ISSUE THREAD

**Issue by curtsheller** [kodeine/laravel-acl#72]
How can this be resolved?

**Comment by kodeine** [comment]
#66 
@curtsheller 
Your composer.json should have "kodeine/laravel-acl": "~1.0@dev", not the dev-master branch.

**Comment by curtsheller** [comment]
Curt Sheller
curt@curtsheller.com
curt@funkyfrets.com
curtsheller@gmail.com

> On Jul 2, 2015, at 1:52 PM, Kodeine <notifications@github.com> wrote:
> 
> #66 <https://github.com/kodeine/laravel-acl/issues/66> 
> @curtsheller <https://github.com/curtsheller> 
> Your composer.json should have "kodeine/laravel-acl": "~1.0@dev", not the dev-master branch.

That is not what is on the installation <https://github.com/kodeine/laravel-acl/wiki/Installation> instructions: 

"kodeine/laravel-acl" : "dev-master"


And, this is what I get if I use the ~1.0@dev.

The blade extension are echoed out.

@role('admin')
 IN role('admin')
@endrole @role('student')
 IN role('student')
@endrole @role('admin|gold')
 IN role('admin|gold')
 Content only for admin and gold members
@endrole @role('bronze')
 IN role('bronze')
 Content for bronze members
@endrole @role('silver')
 IN role('silver')
 Content for silver members
@endrole

It is OK using dev-master.

I’ve been using the package awhile and really like it - however in trying to resolve some composer issues on my dev machine I was trying to get rid of this.



Curt

**Comment by kodeine** [comment]
@curtsheller 
master branch is being developed. 1.0 branch is stable, so i advice you to use ~1.0 branch.
i will work on master and fix blade issue soon.

**Comment by kodeine** [comment]
@curtsheller 
so blade works fine on master?

**Comment by curtsheller** [comment]
Blade is working on "dev-master".
