### ISSUE TITLE
Protect Routes Wiki is confusing, no sense

### ISSUE THREAD

**Issue by fishmad** [kodeine/laravel-acl#75]
Can you please provide a more simple example ie admin (full permissions), editor (limited) and registered user (view only)  on say a model called albums with basic artist, album, title, year - I've just about given up trying to make anything work based on protected route instructions.

**Comment by wdog** [comment]
yes please I also need some simple example on how to use ACL , mostly with custom methods (not verbs)

thanks a lot for your time!
