### ISSUE TITLE
dev-master L5.0 compatibility

### ISSUE THREAD

**Issue by EHLOVader** [kodeine/laravel-acl#76]
I tried dev-master to use the blade extensions. It doesn't work. Extending blade was changed in 5.1 and it appears `Blade::directive` didn't exist in 5.0.

It looks like you want to maintain backwards compatibility to L5.0 from the changelog but it appears the blade extensions will complicate that.

See [Laravel Upgrade Guide- 5.1.0- Blade](http://laravel.com/docs/master/upgrade#upgrade-5.1.0) for more details on the changes.

**Comment by kodeine** [comment]
@EHLOVader please try ~v1.0
