### ISSUE TITLE
cant use kodeine's  methods using controller

### ISSUE THREAD

**Issue by rahul9874563210** [kodeine/laravel-acl#77]
I using kodeine package with larave 5 and  i'm trying to assign role  to a specific user but it doesn't works .
i have done all the required setups correctly. When is use php artisan tinker it works but accessing from controller it doesn't.
i'm getting error 
Call to undefined method Illuminate\Database\Eloquent\Collection::assignRole()
.
My RolesController.php is as follow:
<?php namespace App\Http\Controllers;

use App\User;
use Kodeine\Acl\Models\Eloquent\Role;
use App\Http\Requests;
use App\Http\Requests\RoleRequest;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;

/**
 * Class RolesController
 * @package App\Http\Controllers
 */
class RolesController extends Controller {

    public function __construct()
    {
        $this->middleware('auth', ['except'=>['index', 'show']]);
    }
	

    public function assignUserStore(Requests\AssignRoleToUserRequest $request){
        $user=User::find($request->only('user'));
        $role=Role::findOrFail($request->only('role'));
        $user->assignRole($role->id);
        flash()->success('Role has been successfully assigned to the user');
        return redirect('roles');
    }
.

}

**Comment by andreiculda** [comment]
instead of 
$user->assignRole($role->id);
try
$user->assignRole($role);
