### ISSUE TITLE
Compatibility with laravel 5.1

### ISSUE THREAD

**Issue by arebah** [kodeine/laravel-acl#78]
hello
Thank you for your time designed to develop this wonderful package.

I have a problem of compatibility with Laravel 5.1.8 I have this error:

BadMethodCallException Builder.php line in 2003: Call to undefined method Illuminate \ Database \ Query \ Builder :: is ()

Regards,

**Comment by kodeine** [comment]
@arebah 
can you please paste your code so i can replicate here and give it a try?

**Comment by arebah** [comment]
I have not added your documentation I followed to the letter with the
5.1.8 version
of Laravel.

Cordialy,

---------------------------------------------------------------
*ADIL REBAH*
*Leader Technique confirmé*
MOBILE :
*+212 (0) 662 165 333*FIX       : *+212 (0) 522 758 131*
---------------------------------------------------------------

2015-08-05 14:36 GMT+01:00 Kodeine <notifications@github.com>:

**Comment by m4gn3to** [comment]
Hi.

I've been trying to use kodeine but always get the same error:


BadMethodCallException Builder.php line in 2003: Call to undefined method Illuminate \ Database \ Query \ Builder :: is ()

I cand send you the full code 

I'm using laravel 5.1

**Comment by Hobstweedl** [comment]
I just ran into this issue with a fresh install of Laravel 5.2.20 although the error is slightly different.

**BadMethodCallException in Builder.php line 2161:
Call to undefined method Illuminate\Database\Query\Builder::is()**

Happens when I add the line `$check = Auth::user()->is('admin');` to my controller.

**Comment by kodeine** [comment]
@Hobstweedl 
can you try ->isAdmin and see if its the same?

**Comment by Hobstweedl** [comment]
isAdmin() works just fine. I'm also finding the same issue is coming up with assignRole

**BadMethodCallException in Builder.php line 2161:
Call to undefined method Illuminate\Database\Query\Builder::assignRole()**

```
	$role = new Role();
	$roleModerator = $role->create([
	    'name' => 'Moderator',
	    'slug' => 'moderator',
	    'description' => 'manage moderator privileges'
	]);
	
	$user = User::find(1);
	$user->assignRole($roleModerator);
```

**Comment by kodeine** [comment]
@Hobstweedl 
i dont have l5.2 installed locally so cant test right away, if you find any fix meanwhile please do let me know or send a pr.

**Comment by jrran90** [comment]
Hello, I've got same problem with @Hobstweedl regarding assignRole function.
Here's the error

FatalErrorException in Builder.php line 1392:
Call to a member function compileSelect() on a non-object

Hoping for a response, thanks :)
