### ISSUE TITLE
Question about protecting routes

### ISSUE THREAD

**Issue by goranata** [kodeine/laravel-acl#79]
Hello,

I have a question about using is => 'roleslug'

is it possible, somehow to use is => ['roleslug1', 'roleslug2']

because all I get is an error so far ?

**Comment by kodeine** [comment]
Refer to the wiki at 

https://github.com/kodeine/laravel-acl/wiki/Validate-Permissions-and-Roles

**Comment by goranata** [comment]
THank You for the quick reply but, I'm still getting an error:

I'm trying to make something like this: 
Route::group(['namespace' => 'User', 'prefix' => 'user', 'middleware' => ['auth', 'acl'], 'is' => ('partyhost'|'partygoer')], function() {
/// routes come here ...
}

**Comment by kodeine** [comment]
@goranata
`is` should be like this  `'is' => 'partyhost|partygoer'`

**Comment by goranata** [comment]
Didn't crossed my mind for this.
Thank you very much, that's it. Solved.
