### ISSUE TITLE
Advice for creating role class

### ISSUE THREAD

**Issue by kbhatt2006** [kodeine/laravel-acl#8]
Hi

excuse for my ignorance, but how shall I create role ? do i have to create app/role.php like this..

``` php

<?php namespace App;

use Illuminate\Auth\Authenticatable;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Auth\Passwords\CanResetPassword;
use Illuminate\Contracts\Auth\Authenticatable as AuthenticatableContract;
use Illuminate\Contracts\Auth\CanResetPassword as CanResetPasswordContract;

use Kodeine\Acl\Traits\HasRole;

class Role extends Model {

$role = new Role();
$roleAdmin = $role->create([
    'name' => 'Administrator',
    'slug' => 'administrator',
    'description'=>'manage administration privileges'
]);

$role = new Role();
$roleModerator = $role->create([
    'name' => 'Moderator',
    'slug' => 'moderator',
    'description'=>'manage moderator privileges'
]);
}
```

How do I check that roles and permissions are created ?

and simliarly must I create app/permission.php ?

I already have one user and which can login with default auth...
How should I pass role and permission as admin to this existing user?

advice pls :)
Thank you

**Comment by kodeine** [comment]
@kbhatt2006, If you want to allow admin to create roles from panel, you should make a controller and in that you should call the role creation you mentioned. Otherwise just seed your database with few roles and permissions you need. you can validate roles for existing role using this ... Auth::user()->can('permission') or Auth::user()->is('role')

**Comment by rzimin** [comment]
@kbhatt2006 You can also do this by using tinker, so to avoid creating new files.
`php artisan tinker`

**Comment by kbhatt2006** [comment]
@kodeine Thanks, then I must create CRUDcontroller mentioning all roles and permissions , which can be synced(edit,delete,create user..etc) with migrated database. Correct me if this not viable.

**Comment by kodeine** [comment]
Sure you can make a single controller or maybe make a seed file, because roles and permissions will be added once and they will be used again n again. So either way you're good.
