### ISSUE TITLE
App\Http\Kodeine\Acl\Middleware\HasPermission does not exist

### ISSUE THREAD

**Issue by tritontek** [kodeine/laravel-acl#80]
Hi guys, can you help me? I'm using Laravel 5.1. And I tried to integrate this library (laravel-acl) to my project. But when I run my project using the route which I protected by laravel-acl, this will popup to my screen "App\Http\Kodeine\Acl\Middleware\HasPermission".

I already tried adding this "'acl' => Kodeine\Acl\Middleware\HasPermission::class," in my Kernel.php in the $royeMiddleware array. Do you have any solution for this?

Thanks

**Comment by Rtransat** [comment]
Try:

```php
'acl' => \Kodeine\Acl\Middleware\HasPermission::class
```

**Comment by kodeine** [comment]
@tritontek 
was this solved ?

**Comment by udemethegrtman** [comment]
@tritontek  in your route add the slash to the front of the class path, like this `\Kodeine\Acl\Middleware\HasPermission::class`  instead of  "Kodeine\Acl\Middleware\HasPermission" it worked for me, you try it.

**Comment by tarhe** [comment]
In Kernel.php, change:

`'acl' => Kodeine\Acl\Middleware\HasPermission::class,`

to

`'acl' => 'Kodeine\Acl\Middleware\HasPermission',`

Hope that helps
