### ISSUE TITLE
Function addPermission from trait HasUserPermission

### ISSUE THREAD

**Issue by rptgit** [kodeine/laravel-acl#87]
I was looking for a function to create permissions for specific models but i've noticed the function addPermission from trait HasUserPermission can't create a new permission with custom values in a single executions.

For example, the function

$user->addPermission('custom', [
     'create' => false,
     'view.phone' => true, 
     'view.blog' => false
]);

will create a record with default crud permissions and without custom values. For the expected values I need to execute the function a second time to update the row.

Is it working as intended?

**Comment by kodeine** [comment]
@rptgit 
i would have to test this.
