### ISSUE TITLE
Advise for validating permission

### ISSUE THREAD

**Issue by mikhi** [kodeine/laravel-acl#9]
Hi Kodeine, 
i can't figure out witch is the best way to validate user permission. All my controllers will extends an base controller, where i want to check if user has permission to access the specific methods...
Here is my code:
...
class BaseController extends Controller {

    protected $user;

    public function __construct(Route $route){

        //set middlewares
        $this->middleware('auth');
        $this->middleware('acl');

        //get loggedin user
        $this->user = Auth::user();

        //get current method
        $permission = $route->getActionName(); 

       /*here is my issue: i dont know how to validate permission based on your provided examples: Auth::user->can('view.user');
     */

        //validate current permission
        if (!$this->user->can($permission)) abort(403);        
}

Is this scenario wrong? Please help me with your advise!
Thank you!

**Comment by kodeine** [comment]
@mikhi,
i guess you are trying to protect routes. You dont have to do that since its already done in ACL. 
refer to [protect routes wiki](https://github.com/kodeine/laravel-acl/wiki/Protect-Routes)

**Comment by mikhi** [comment]
ok, thanks for advise.

**Comment by kodeine** [comment]
@mikhi let me know if there is anything we can help with :)
