### ISSUE TITLE
Permission Inheritance

### ISSUE THREAD

**Issue by parallelaus** [kodeine/laravel-acl#93]
I am finding the if the base permission is set to true, and an inherited permission set to false, the false does not override the true. 

The opposite way however, does work, if the base permission is set to false and the inherited permission is set to true it works.

E.g. The following always produces true permissions for create, update and delete even though the user only has the organisation.facilities-manager role. If I reverse the logic, set permissions to false in the base permission (organisation) and I set view=>true in the child permission, it works as expected.

    	// Organisation Permissions
		$permOrganisation = Permission::create([
			'name'	=> 'organisation',
			'slug'	=> [
				'create' => true,
				'view'   => true,
				'update' => true,
				'delete' => true,
			],
			'description'	=> 'Manage Organisation'
		]);
	
		Permission::create([
				'name'	=> 'organisation.facilities-manager',
				'slug'	=> [
					'create' => false,
					'update' => false,
					'delete' => false,
				],
				'inherit_id'	=> $permOrganisation->getKey(),
				'description'	=> 'Facilities Manager Organisation Permissions',
		]);

I followed the example in the Wiki:
      $permissionInternship = Permission::create([
            'name'        => 'internships',
            'slug'        => [ // an array of permissions.
                'create' => true,
                'view'   => true,
                'update' => true,
                'delete' => true,
            ],
            'description' => 'manage internships'
        ]);

        $permissionStudent = Permission::create([
            'name'        => 'internships.student',
            'slug'        => [ // an array of permissions only for student
                'create' => false,
            ],
            // we use permission inheriting.
            'inherit_id' => $permissionInternship->getKey(),
            'description' => 'student internship permissions'
        ]);

**Comment by kodeine** [comment]
@parallelaus
Did you try setting `most permissive` to false in acl config?

**Comment by parallelaus** [comment]
Thanks - That solved the issue!

What does ntfs stand for?

**Comment by kodeine** [comment]
@parallelaus
If you have multiple roles assigned to a user, each roles has a common permission. When we compile permissions, we need to know if Allow|Deny permissions take precedence over Deny|Allow permissions.

**Comment by kodeine** [comment]
@parallelaus please close the issue if everything is okay.
