### ISSUE TITLE
Ternary Operator 

### ISSUE THREAD

**Issue by wdog** [kodeine/laravel-acl#94]
maybe i'm wrong ( sorry for this ) but this does not work 

(https://github.com/kodeine/laravel-acl/blob/1.0/src/Kodeine/Acl/Middleware/HasPermission.php)
there's no way to obtain $methods variable

```
   $methods = is_array($methods) ? $methods :
            in_array($caller, $resources) ?
                $this->crud['resource'] : $this->crud['restful'];
```

http://phpsadness.com/sad/30
please help me to understand this part of code in the middleware

thanks!

**Comment by wdog** [comment]
I think that in the same Middleware i've found a typo

```
HasPermission.php:101:        $resources = $this->crud['resources'];
HasPermission.php:120:                $this->crud['resource'] : $this->crud['restful'];
HasPermission.php:224:            $this->crud['resource'] = $resource;
```

sometimes is resource and sometime is resources (parseMethod and crudConfigOverride )

**Comment by kodeine** [comment]
@wdog 
$methods has a function call, `$methods = $this->getAction('protect_methods');`

**Comment by wdog** [comment]
what I mean is that this ternary operator does not work 
```
// wrong
$a = is_array($a) ? $a : is_array($b): $c : $d 
// right
$a = is_array($a) ? $a : (is_array($b): $c : $d )
```

and what i don't understand is a real use of protect_methods. can you write simple example? 
with methods names and not with placeholders.

thanks a lot

**Comment by kodeine** [comment]
@wdog 
i'll fix the ternary operator. 
for `protect_methods` read this [wiki](https://github.com/kodeine/laravel-acl/wiki/Protect-Routes)

**Comment by kodeine** [comment]
@wdog ternary operator is fixed.
